### ISSUE TITLE
peer closed connection in SSL handshake while fetching SSL session by lua

### ISSUE THREAD

**Issue by cltxiaoyao** [openresty/lua-resty-redis#100]
session_fetch.lua code:

1. print("into session_fetch")
2. 
3. local redis = require("redis_instanse")
4. 
5. local ngx_ssl_session = require "ngx.ssl.session" 
6. 
7. local key, err = ngx_ssl_session.get_session_id() 
8. print("key" .. key)
9. if not key then 
10.    ngx.log(ngx.ERR, "failed to get SSL session ID: ", key) 
11. return 
12. end 
13. 
14. cache = redis:get_redis()
15. local session = cache:get(key)

when run the code number 14 and 15,the error.log  shows:
peer closed connection in SSL handshake while fetching SSL session by lua

**Comment by cltxiaoyao** [comment]
I write a test code.
ceshi.lua

local redis = require "resty.redis"
local red = redis:new()

red:set_timeout(3000) 
print("connect redis start")	

local ok, err = red:connect("10.171.122.122", 6379)
print("connect redis end")
if not ok then
	ngx.say("failed to connect: ", err)
	return
end

ok, err = red:set("dog", "an animal")
if not ok then
	ngx.say("failed to set dog: ", err)
	return
end

The nginx.conf  like this:
![image](https://cloud.githubusercontent.com/assets/22709589/19220717/b40cec52-8e66-11e6-90d3-c93e50911a71.png)

The error.log is also:
![image](https://cloud.githubusercontent.com/assets/22709589/19220731/dc8b531c-8e66-11e6-910b-f53974fef608.png)

So what should I do to resolve the problem?

**Comment by agentzh** [comment]
@cltxiaoyao Looks like it's the client closing the SSL connection, not the server. Note the error log message you quoted has the "info" level, so not even a warning, not to mention an error.

BTW, you need to put `ssl_session_fetch_by_lua*` (and also `ssl_session_store_by_lua*`) on the `http {}` level if you have several SSL virtual servers defined in your `http {}` block.

Also ensure you are using the OpenResty release here:

http://openresty.org/en/download.html

Your error message may also indicate that you are using a stock nginx core which does not support this `ssl_session_fetch_by_lua*` directive.

**Comment by cltxiaoyao** [comment]
I update the OpenResty to version 1.11. 2.1, the problem is not exist now. Maybe the OpenResty 1.9. 15.1 I used doesn't support ssl_session_fetch_by_lua* directive. Thank you very much.

**Comment by agentzh** [comment]
@cltxiaoyao True. That feature was added since OpenResty 1.11.2.1. Whenever in doubt, read the documentation and/or check the change logs.
