### ISSUE TITLE
请问，可以缓存redis连接吗？

### ISSUE THREAD

**Issue by githublaohu** [openresty/lua-resty-redis#103]
syntax: ok, err = red:connect(host, port, options_table?)
这是创建连接，我可以把创建的连接缓存起来吗？

**Comment by githublaohu** [comment]
每次请求是不是回去创建一个 lua的环境？

**Comment by spacewander** [comment]
这里只讨论 bug，feature 或其他 lua-resty-redis 开发相关的问题。

使用上的问题请移步到 OpenResty 中文邮件组：
https://groups.google.com/group/openresty

**Comment by agentzh** [comment]
@githublaohu Please, no Chinese here.

Regarding your question, read the official documentation:

https://github.com/openresty/lua-resty-redis#connect

https://github.com/openresty/lua-resty-redis#set_keepalive

**Comment by githublaohu** [comment]
多谢，还是有点模糊。
请问下。 ngx.socket的这个模块在哪里。想去看看代码。
多谢。
