### ISSUE TITLE
lua entry thread aborted: runtime error:bad request

### ISSUE THREAD

**Issue by laoshancun** [openresty/lua-resty-redis#104]
hi,i got this error.
```
2016/12/10 10:21:50 [error] 22017#0: *30467564
lua entry thread aborted: runtime error: /etc/nginx/lua/ngx_lua_waf/redis.lua:253: bad request#012
stack traceback:
#012coroutine 0:#012#011[C]: in function 'send'
#012#011/etc/nginx/lua/ngx_lua_waf/redis.lua:253: in function </etc/nginx/lua/ngx_lua_waf/redis.lua:235>
#012#011(tail call): ?
#012#011/etc/nginx/lua/ngx_lua_waf/provider.lua:106: in function 'is_in_whitelist'
#012#011/etc/nginx/lua/ngx_lua_waf/waf.lua:21: in function 'whiteip'
#012#011/etc/nginx/lua/ngx_lua_waf/waf.lua:41: in function </etc/nginx/lua/ngx_lua_waf/waf.lua:1>, 
client: 192.168.0.4, server: www.test.com, request: "POST /test?action=get_list HTTP/1.1", host: "www.test.com"
```

**Comment by agentzh** [comment]
@laoshancun This is a FAQ. Just stop sharing your resty.redis object across your Lua request handler boundary.

**Comment by wgh000** [comment]
@agentzh sorry to resume this issue after one year. I'm having the same issue, only with concurrent requests. What you exaclty mean with "stop sharing your resty.redis object across your Lua request handler boundary"?

**Comment by agentzh** [comment]
@wgh000 It means that request B's Lua code tries to use the `resty.redis` object created in request A's context.

**Comment by wgh000** [comment]
Yes, I understood that. I cannot understand what's the better way to 
prevent this. Where is better to declare the Redis object?

**Comment by agentzh** [comment]
@wgh000 You should avoid sharing `resty.redis` objects on the Lua module level since such data is shared across all concurrent requests. See

https://github.com/openresty/lua-nginx-module/#data-sharing-within-an-nginx-worker

Always pass the object via function call arguments or as a "self" object in the OO syntax.

**Comment by agentzh** [comment]
@wgh000 Basically you should create a new `resty.redis` object on every request and only recycle the underlying TCP connections across different nginx request handlers via the `set_keepalive()` call.
