### ISSUE TITLE
ERR syntax error

### ISSUE THREAD

**Issue by zhangchunsheng** [openresty/lua-resty-redis#105]
I got this error "ERR syntax error" when I set a json string

code like below

self.conn:set(key, val, expire)

**Comment by zhangchunsheng** [comment]
I removed expire arg, then it worked.

self.conn:set(key, val)

**Comment by spacewander** [comment]
@zhangchunsheng 
Please read the documentation of redis `set` command:
https://redis.io/commands/set

What you need may be:
```
self.conn:set(key, val, 'EX', expire)
```

**Comment by zhangchunsheng** [comment]
Ok, I get that.
