### ISSUE TITLE
connection refused 

### ISSUE THREAD

**Issue by myselfghost** [openresty/lua-resty-redis#106]
if timeout  is 5 sec,
it still wait 5s when redis is connection refused .

It should throw an error immediately when redis is  connection refused .

**Comment by agentzh** [comment]
@myselfghost I've just added a test case to this library's test suite for this connection refused case and it works as expected:

https://github.com/openresty/lua-resty-redis/blob/master/t/sanity.t#L833

As you can see, it returns the "connection refused" error upon the `connect()` call immediately without waiting for any longer.

**Comment by myselfghost** [comment]
I am sorry ,i find the problem.

because the condition of the routing problem,redis connection timed out for more than 5sec.

not because  connection refused
