### ISSUE TITLE
incr command return wrong value

### ISSUE THREAD

**Issue by Magiczml** [openresty/lua-resty-redis#107]
Hello, Openresty is very good framework, but i get some trouble, when i use incr command, the function return wrong value. run first return 1, run twice return 3, but 2 is right value. please check the code.

    local redis = require "resty.redis"
    local red = redis:new()
    red:set_timeout(1000) 

    local ok, err = red:connect(etc.redis_host, etc.redis_port)

    if not ok then
         ngx.exec("@old")
         return
    end

    local value = red:incr(self._etc.uuid_key)
    return value

**Comment by agentzh** [comment]
@Magiczml Check the code? There is really nothing for us to check since this client does not even make sense of the "incr" name! :)

You'd better provide a *minimal* and *standalone* example that can can easily reproduce the problem on our side. Otherwise we don't know how we can help.

**Comment by Magiczml** [comment]
I'm sorry for my poor english, i mean you can look our example code.

```
resty redis example:
local value = red:incr(self._etc.uuid_key)
return value

in redis client:
127.0.0.1:6379[1]> incr example
(integer) 1
127.0.0.1:6379[1]> incr example
(integer) 2
```

i think may be run incr twice.

**Comment by spacewander** [comment]
@Magiczml 
I could not reproduce the issue with:
```
#!/usr/bin/env resty
local redis = require "resty.redis"
local red = redis:new()
red:set_timeout(1000)

local ok, err = red:connect('127.0.0.1', 6379)

if not ok then
    ngx.say(err)
    return
end

local value = red:incr('k')
ngx.say(value)
```

Result:
```
☁  /tmp  ./t.lua
1
☁  /tmp  ./t.lua
2
```

Is there something missing in my case?

**Comment by Magiczml** [comment]
@spacewander i catch the bug, because when i request the blank page in the Chrome. include two request(document and favicon.ico), so INCR tigger twice.

**Comment by Magiczml** [comment]
@agentzh @spacewander thank you for you help!
