### ISSUE TITLE
hmget fields

### ISSUE THREAD

**Issue by Roycohen** [openresty/lua-resty-redis#109]
Hi There,

I want to use hmget to get several fields.
The problem is that hmget gets the key and field,field,field by delimiter.
I want to make it recursively via code.

Assume that I have an array of fields and I want to get them in one call.

local fields = {'dog', 'cat', hourse'}
red:hmget(field, fields)

How can I achieve that?
Thanks

**Comment by agentzh** [comment]
@Roycohen In your use case, you can just use the `unpack` Lua builtin function to expand your table arguments.

But yeah, it might be more efficient to support table-typed arguments directly there. Patches welcome.

**Comment by Roycohen** [comment]
Hi @agentzh,

I'll try to make a patch.
thanks for the unpack thing, it is working just like magic.
