### ISSUE TITLE
Missing nginx config file

### ISSUE THREAD

**Issue by josegonzalez** [openresty/lua-resty-redis#11]
This file is necessary to install `lua-resty-redis` into a custom nginx compilation. Is it available somewhere, or is this meant to be part of another module somehow?

**Comment by Mahanteshambi** [comment]
Hey @agentzh : I am using openresty to configure nginx to communicate to redis sentinels. But I am unable to connect to them as it says "no field package ['resty.redis.connector']" . Can you suggest a solution for connecting nginx with redis sentinels ?

**Comment by agentzh** [comment]
@Mahanteshambi Please do not hijack unrelated issues like this. It's annoying. Your questions should post to the openresty-en mailing list instead. See http://openresty.org/en/community.html
