### ISSUE TITLE
hscan

### ISSUE THREAD

**Issue by Roycohen** [openresty/lua-resty-redis#110]
Hi @agentzh,

I can't figure how you would use the cursor in hscan and scan commands.
Can you please give me an example on how to iterate over keys in a do .. while, context.

Thanks

**Comment by spacewander** [comment]
First of all, the issue tracker is only for bug report. For general question, please join the OpenResty mail list.

You could store the cursor returned from last `scan`, and make the next call with it.
 
```lua
local json = require "cjson"
local redis = require "resty.redis"

local red = redis:new()
red:connect('127.0.0.1', 6379)
local cursor = "0"
repeat
    local date, err = red:scan(cursor)
    if not date then
        ngx.say(err)
        break
    end
    cursor = date[1]
    ngx.say(json.encode(date))
until cursor == "0"
```

**Comment by Roycohen** [comment]
Hi @spacewander,

I'll join the group, but it would be great if you could show me how to do that in hscan.
I can't figure it out.
I have something like the following:

`
local cursor = "0"

repeat
	local res, err = red:hscan(cursor, "user-" .. id, cursor, 0, "count", 100)
	if not res then
		ngx.log(ngx.ERR, "failed to scan: " .. err)
		ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
	end

	local keys, err
	cursor, keys, err = unpack(res)
until(cursor == 0 or cursor == "0")

`

And I'm getting  "ERR invalid cursor"
What am I missing?

**Comment by spacewander** [comment]
@Roycohen 
```
local cursor = "0"
repeat
    local res, err = red:hscan("user-" .. id, cursor, "count", 100)
    if not res then
        ngx.log(ngx.ERR, "failed to hscan: ", err)
        ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
    end

    local data
    cursor, data = unpack(res)
    ngx.say(json.encode(data))
until cursor == "0"
```

**Comment by Roycohen** [comment]
@spacewander 
THANKS!
Working great!!
