### ISSUE TITLE
unkown prefix: "72"

### ISSUE THREAD

**Issue by GuaiShu** [openresty/lua-resty-redis#111]
春哥，我把概要中的例子脚本直接抄下来测试，当执行到 ok, err = red:set("dog", "an animal")时，总是不成功。返回的err信息为 unkown prefix: "72"
看起来像是环境配置的问题。能帮我看看吗

**Comment by spacewander** [comment]
Is it related with that issue?
https://github.com/CodisLabs/codis/issues/336

**Comment by GuaiShu** [comment]
@spacewander thanks.
