### ISSUE TITLE
add method about sadd(key,table)

### ISSUE THREAD

**Issue by BlackGhostKing** [openresty/lua-resty-redis#112]
i hope to  add sadd(key,table) to resty.redis.lua,thanks!

**Comment by spacewander** [comment]
Why not call with `sadd(key, unpack(table))`?

**Comment by dingyo** [comment]
i used sadd(key, unpack(table)), but i found only the first value in the table insert into the redis

**Comment by dingyo** [comment]
@spacewander  i used sadd(key, unpack(table)), but i found only the first value in the table insert into the redis

**Comment by agentzh** [comment]
Consider it resolved.
