### ISSUE TITLE
Is it possible to connect redis in _do_cmd function?

### ISSUE THREAD

**Issue by kenuyx** [openresty/lua-resty-redis#114]
I don't know if it is a good practice to directly call redis command right after `new` function is called. I think in this way some duplicate code can be avoided when using this library. 

What I think is something like this.

```
function _M.new(self, opts)
    local sock, err = tcp()
    if not sock then
        return nil, err
    end
    return setmetatable({ _sock = sock, _subscribed = false, _opts = opts }, mt)
end

local function _do_cmd(self, ...)
    local args = {...}

    local sock = rawget(self, "_sock")
    if not sock then
        return nil, "not initialized"
    end
    
    # connect if _opts is not nil
    local opts = rawget(self, "_opts")
    if opts then
        self.connect(opts.host or "127.0.0.1", opts.port or 6379)
        self.set_timeout((opts.timeout and opts.timeout * 1000) or 1000)
    end
    
    local req = _gen_req(args)

    # skip unaltered part

    local bytes, err = sock:send(req)
    if not bytes then
        return nil, err
    end

    # setkeepalive if _opts is not nil
    local res, err = _read_reply(self, sock)
    if opts then
        self.set_keepalive(opts.conn_pool_size or 10000, opts.max_idle_time or 100)
    end
    return res, err
end
```

I hope my code above can well explain my thought. Thx.

**Comment by spacewander** [comment]
@kenuyx 
It would be better to write your wrapper instead of changing the library. For instance, you can subclass `redis`, and hide other calls in a custom `__index` method.

In my opinion, cram too much thing to `_do_cmd` will make it difficult to reuse. A more clear interface is better then a shorter code.

**Comment by kenuyx** [comment]
Em, I agree with you after I think it over. Thank you for your answer.
