### ISSUE TITLE
set_keepalive limit

### ISSUE THREAD

**Issue by samuelyao314** [openresty/lua-resty-redis#115]
set_keepalive only opend when ngnix configure has "lua_code_cache on; ".  I think it must be documented.

**Comment by spacewander** [comment]
When `lua_code_cache` is off, OpenResty set up a new lua vm for every request.
Since each request use a separate lua VM, there are many unexpected situations with `lua_code_cache` turned off.

So you should use `lua_code_cache off` only when you want to compare the response with request quickly.

**Comment by agentzh** [comment]
@samuelyao314 You should never ever use `lua_code_cache off` in production. It's for quick development ONLY. And I don't think you want to care about connection pool in this case in the first palce.
