### ISSUE TITLE
not working with resty-cli

### ISSUE THREAD

**Issue by henriquechehad** [openresty/lua-resty-redis#120]
I'm trying to use the project running with resty-cli but it doesn't connect to the redis server and not return error too.

Example:
```
    local resty_redis = require 'resty.redis'
    local redis = resty_redis:new()

    local ok, err = redis:connect("redis", 6379)
    if not ok then
        ngx.say("failed to connect: ", err)
    end
```

The variable `ok` returns always `true` and the var `err` returns `nil`. I tested with correct connection host/port and wrong (to see if would return an error) too.

**Comment by agentzh** [comment]
@henriquechehad If `connect()` does not return an error, then there is no error in this operation. You should check the error of your first failed subsequent operation *after* `connect()`.

**Comment by agentzh** [comment]
@henriquechehad I noted that you use `redis` as the host name. Why don't you try IP address there? BTW, `/etc/hosts` file is not supported in OpenResty by default yet.

**Comment by agentzh** [comment]
@henriquechehad Running your example directly on my side with the `resty` utility gives the following error:

```
failed to connect: redis could not be resolved (3: Host not found)
```

**Comment by agentzh** [comment]
@henriquechehad I just tried the following standalone Lua script with the `resty` utility on my side:

```lua
local resty_redis = require 'resty.redis'
local red = resty_redis:new()

local ok, err = red:connect("127.0.0.1", 6379)
if not ok then
    ngx.say("failed to connect: ", err)
    return
end

ok, err = red:set("dog", "an animal")
if not ok then
    ngx.say("failed to set dog: ", err)
    return
end

ngx.say("set result: ", ok)

local res, err = red:get("dog")
if not res then
    ngx.say("failed to get dog: ", err)
    return
end

if res == ngx.null then
    ngx.say("dog not found.")
    return
end

ngx.say("dog: ", res)
```

It works correctly:

```
$ resty a.lua
set result: OK
dog: an animal
```

I have a redis-server listening on the local port 6379. You can try this example on your side as well. If you still believe there is an issue in OpenResty, please prepare a standalone and minimal example that can easily reproduce the problem on our side, just like my code example demonstrated above. Do not make us guess. Thank you!

**Comment by henriquechehad** [comment]
@agentzh thank you a lot for helping! It's true, I tested now the code in a separated file and worked well, but when I try inside the spec file (i'm using busted for tests and running with resty-cli) it doesn't work... I'm debugging

**Comment by henriquechehad** [comment]
it was a tcp mock in the project code interfering, it's not library error. 
thanks, closing the issue.

**Comment by agentzh** [comment]
@henriquechehad Alas. What a waste of my time :)
