### ISSUE TITLE
i get a connect from redis:connect, how to get this connect selected dbindex?or this connection from pool or create?

### ISSUE THREAD

**Issue by mikawudi** [openresty/lua-resty-redis#122]
when i get connection from i call redis:connect method, i don't know this connection is a new connection or it from connection pool,if it from connection pool, i don't want to repeat call redis:select, (when the connection created, i call select first),so i wan't to know this connection from pool or create, or this connection selectd db index now. could you give me some demo about this......i am a chinese and not good at english TAT

**Comment by spacewander** [comment]
Here is an API to tell if a connection is reused:
https://github.com/openresty/lua-resty-redis#get_reused_times

And you can customize pool option in `connect` to identify selected db index.
https://github.com/openresty/lua-resty-redis#connect

Like this:
```lua
local ok, err = red:connect(_M.ip, _M.port,
        {pool = _M.ip..'#'.._M.port..'#select#'..idx})
```

**Comment by mikawudi** [comment]
oh~thanks very much
