### ISSUE TITLE
"unsubscribe" order return "message"

### ISSUE THREAD

**Issue by dogagithub** [openresty/lua-resty-redis#125]
```lua
    local un, err = red:unsubscribe(sChannel)
    if not un then
        ngx.log(ngx.ERR, "unsubscribe err: ", err, sChannel, msg)
    end
    ngx.log(ngx.WARN, "1: unsubscribe: ", sChannel, cjson.encode(un))
```
2017/07/28 07:59:15 [warn] 2122#2122: *2 [lua] redis.lua:172: request(): 1: unsubscribe: ROOM_MANAGER_GF_1["message","ROOM_MANAGER_GF_1","[\"enterRoom\",{\"code\":500}]"], context: ngx.timer

**Comment by agentzh** [comment]
@dogagithub It looks normal to me since you just have unread or newly entered published messages in that channel when you're doing unsubscribe. Be aware of the full duplexing nature of a TCP connection.
