### ISSUE TITLE
Redis command set by string variable?

### ISSUE THREAD

**Issue by abagshaw** [openresty/lua-resty-redis#128]
If I want to execute a certain Redis command as dictated by a string is there some `raw()` function or equivalent that will provide this functionality?

For example instead of this:
`ok, err = red:set("dog", "an animal")`

I'd like to use this:
`ok, err = red:raw("set", "dog", "an animal")`

That way I can replace `"set"` with a variable that can dynamically change to whatever command I need. Any way to do this?

**Comment by agentzh** [comment]
@abagshaw Well, you can do this:

```
red["set"](red, "dog", "an animal")
```

It's just Lua syntax basics. Basically, `red:set(...)` is equivalent to `red.set(red, ...)`. Nothing special here.
