### ISSUE TITLE
tcpsock:settimeouts not working as expected

### ISSUE THREAD

**Issue by revintec** [openresty/lua-resty-redis#129]
Hi, I'm using openresty 1.11.2.3(which is the newest version as of writing) on OSX 10.10.5
I've built a websocket server using the following code(pruned to show only the relevant part):
```
local server,err=require("resty.websocket.server"):new()
local data,x,err=server:recv_frame()
local tcp=ngx.socket.tcp()
tcp:settimeouts(1800,1800,2^31)
_,err=tcp:connect("127.0.0.1",8000)
data,err=tcp:receive(1)
if err then return ngx.log(ngx.EMERG,err)end
```
A tcp service is on port 8000, listens and accepts connection, but doesn't reply anything

I expect the webSocket to hang, but it closes after 60secs with the following message:
[emerg] xxx#xxx: *1 [lua] [C]:-1: timeout, client: xxx, server: , request: "GET xxx", host: "xxx"

I'm wondering why my settimeouts call doesn't work, and how I gonna disable the read timeout

**Comment by spacewander** [comment]
@revintec 
Hi, I just move your bug report to https://github.com/openresty/lua-nginx-module/issues/1141.
Because it is more related with `lua-nginx-module`.
We could discuss the problem there.

**Comment by agentzh** [comment]
Considered as duplicate.
