### ISSUE TITLE
Add eval/evalsha abstration

### ISSUE THREAD

**Issue by bakins** [openresty/lua-resty-redis#13]
Inspired by https://github.com/FGRibreau/node-redis-lua

Abstract the eval/evalsha so that user does not have to check if script has been loaded or not.  Also, allow the scripts to be loaded into the module. Something like:

```
redis.import_script('my_special_function', string_with_lua_script)
-- later with red is a redis connection
red.scripts['my_special_function'](1, key, arg, arg, arg)
```

Not sure about the public interface, the above is given as a horrible example.

Thoughts?  If it looks like something that would be generally useful, I can write some code to get it started.

**Comment by TooTallNate** [comment]
>  I'll explore writing an "add on" module that extends lua-resty-redis.

@bakins Was said extension module ever written and/or open-sourced?

**Comment by bakins** [comment]
@TooTallNate work was done at a previous job but not open sourced.  My openresty needs are fairly simple these days, so I haven't used this in quite a while.
