### ISSUE TITLE
Pub/Sub: subscribe to multiple topics does not read all replies from server

### ISSUE THREAD

**Issue by akornatskyy** [openresty/lua-resty-redis#132]
While subscribing to multiple topics the server send confirmation for each. The current implementation assumes a single reply.

```lua
return function()
    local sub = redis:new()

    assert(sub:connect("127.0.0.1", 6379))

    sub:subscribe('topic1', 'topic2')
    local r = sub:read_reply()
    -- prints "subscribe"
    print(r[1])
end
```

Here is trace from tcpflow:

```
$ sudo tcpflow -i lo -c host 127.0.0.1 and port 6379
tcpflow: listening on lo
127.000.000.001.58728-127.000.000.001.06379: *3
$9
subscribe
$6
topic1
$6
topic2

127.000.000.001.06379-127.000.000.001.58728: *3
$9
subscribe
$6
topic1
:1
*3
$9
subscribe
$6
topic2
:2

tcpflow: terminating
```

**Comment by spacewander** [comment]
Maybe we shoud add addition `_read_reply` to address this problem?

**Comment by agentzh** [comment]
@akornatskyy It's your responsibility to keep calling `read_reply()` to get more and more messages.

**Comment by akornatskyy** [comment]
The *subscribe* method supports subscription to multiple topics in a single command, however redis responds separately to each subscription. You expect just one while there might be multiple.
