### ISSUE TITLE
redis:exists() returns 0 when a key doesn't exist, which is "truthy" in lua

### ISSUE THREAD

**Issue by bruce-hill** [openresty/lua-resty-redis#134]
I was writing some code similar to:
`if redis:exists("key") then print("yes it exists") end`
and was surprised to see the branch being entered, even though I knew the key did not exist. This is because in Lua, *all* numbers, including 0, are "truthy" (from the lua docs: "Both nil and false make a condition false; any other value makes it true."), so `redis:exists()` can't be used for a branching conditional without doing `redis:exists() ~= 0`. This is very counterintuitive and can easily lead to bugs. I would recommend making `redis:exists()`, `redis:hexists()`, `redis:sismember()`, and any other similar methods return true/false instead of 1/0.

**Comment by spacewander** [comment]
@bruce-hill 
The redis protocal use integer as the return result of those commands. It may be not a problem in other languages, because they treat 0 as a false value.
I am afraid we could not change the return result of lua-resty-redis API, because it would break a lot of compatibility.

**Comment by agentzh** [comment]
Right, only nil and false are considered a conditional false in Lua. Be careful.
