### ISSUE TITLE
Can I connect redis in the init_by_lua phase?

### ISSUE THREAD

**Issue by krisoul** [openresty/lua-resty-redis#138]
I wonder can we connect redis just for one time while we start the nginx worker, and we can use redis directly in the handler phase.

Like this:

```
init_by_lua_block {
	local redis = require "resty.redis"
	local red = redis:new()

	red:set_timeout(1000) -- 1 sec

	local ok, err = red:connect("127.0.0.1", 6379)
	if not ok then
	    ngx.say("failed to connect: ", err)
	    return
	end

       # set the redis connection pool here.
}

server {

      location / {
          content_by_lua_block {
               local endpoint, err = red:hget("bucket2endpoint", bucket)
               if err then
                     ngx.header.content_type = 'text/plain';
                     ngx.say("failed to get bucket: ", bucket, " ", err)
   	            return
               end
          }
      }
}
```

But it seems can not do it like this, why?

I dont want to connect redis in each request handler.

**Comment by KSDaemon** [comment]
@krisoul AFAIK nginx cosocket API is not available in this phase. See openresty/lua-nginx-module/issues/206

**Comment by krisoul** [comment]
@KSDaemon 
so how can I initialize the redis connection at first but not connect it in every request?

**Comment by agentzh** [comment]
@krisoul lua-resty-redis does support redis connection pools. Check out its `set_keepalive()` method. It makes no sense for `init_by_lua*` to create redis connections in the nginx master process for all its nginx workers to share. You're just looking for the wrong thing.
