### ISSUE TITLE
How to del multiple keys?

### ISSUE THREAD

**Issue by yangxikun** [openresty/lua-resty-redis#139]
`redis:del("key")` just support del one key

**Comment by spacewander** [comment]
@yangxikun 
Does `redis:del("k1", "k2", ...)` work for you?

**Comment by yangxikun** [comment]
I need `redis:del({"k1", "k2"})`. Because key is dynamic.

**Comment by yangxikun** [comment]
Oh， I found another solution, use pipeline……

**Comment by agentzh** [comment]
@yangxikun You could also use the `unpack()` builtin function to expand an array table into an argument list.

**Comment by yangxikun** [comment]
`unpack()` works, thanks!
