### ISSUE TITLE
redis "set_keepalive()" doesnt work, it closes the connection where redis server is running and change the state to TIME_WAIT instead of ESTABLISHED after 2-3 seconds

### ISSUE THREAD

**Issue by rupamkhaitan** [openresty/lua-resty-redis#140]
Here is the sample config file we tried with (exact same code) and on the redis-server which is idle and not doing any other process, it goes into TIME_WAIT after 2 secs, (we did packet capture as well and the box where lua code is running is sending FIN_ACK)

`worker_processes 1;
error_log logs/error.log;
events {
worker_connections 1024;
}

http {
server {
listen 8080;
location /test {
lua_code_cache on;
content_by_lua_block {
local redis = require "resty.redis"
local red = redis:new()
red:set_timeout(500000) -- ms
ok, err = red:connect("10.140.134.38", 6379)
if not ok then
ngx.say("failed to connect redis: ", err)
end
-- ngx.sleep(3) -- tcp status : ESTABLISHED
local ok, err = red:set_keepalive(1000000, 10) -- tcp status : TIME_WAIT
if not ok then
ngx.log(ngx.ERR, "set keep alive error", err);
ngx.say("failed to set keepalive: ", err);
end
}
}
}
}`

**Comment by rupamkhaitan** [comment]
I tried with above sample code with /test location block with same keepalive setting
Our redis server is running on 10.X.X.1
and machine 10.X.X.2 is having the lua location code makes a redis connetion on 10.X.X.1 IP & within 2 seconds we go to the redis machine box and check the netstats.. it shows TIME_WAIT (we see FIN_ACK is sent by the box running the lua code)

netstat -nt | grep 6379

It goes into TIME_WAIT state

**Comment by agentzh** [comment]
@rupamkhaitan cosocket keep-alive connection pool does not limit the concurrency level. It merely reuses those connections not exceeding the connection pool capacity. This means that those exceeding the connection pool will get closed immediately and will not enter the connection pool (because the pool is full already). The official nginx upstream keepalive module shares the same behavior.

So the correct way of checking whether the connection pool works is to check those TCP connections in the ESTABLISHED state, not in the TIME_WAIT state. Since for exceedingly high client concurrent connections, you will surely see TIME_WAIT connection state. This is completely normal.

**Comment by rupamkhaitan** [comment]
There were no high client and only a single connection to redis server.

And the redis server is idle doing nothing.

With one single connection also immediately the state changes to TIME_WAIT .

The expectation is the connection should remain in established state until 100 seconds (thats the config we define in keepalive)

**Comment by rupamkhaitan** [comment]
You can try to setup on your own, just run redis server on one box and on another box run the openresty with above config, the connection will reset to TIME_WAIT

**Comment by agentzh** [comment]
@rupamkhaitan We always have passing tests for keep-alive in our existing test suite:

https://github.com/openresty/lua-resty-redis/blob/master/t/sanity.t#L528

And as you can see, it's always passing on Travis CI, at least:

https://travis-ci.org/openresty/lua-resty-redis

BTW, your redis server might actively close your connections and you should check which side initiates the `close` operation. Temporarily enabling the nginx debugging logs can also give you more details about what's going on under the hood (inside the nginx process).

**Comment by agentzh** [comment]
@rupamkhaitan I just tried your example on my side. I started a redis-server on another machine, as can be seen below, the connection is not closed for several minutes already:

https://gist.github.com/agentzh/3085608ba04bcff2bb6adb49f4a25419

And on the machine running openresty:

```
$ netstat -nt|grep :6379
tcp        0      0 192.168.1.50:38350      192.168.1.8:6379        ESTABLISHED
```

The connection is always there after more than 5 minutes (and still there as I'm writing this).

**Comment by agentzh** [comment]
@rupamkhaitan This is the exact nginx.conf config snippet I'm using:

```nginx
location /test {
    lua_code_cache on;
    content_by_lua_block {
        local redis = require "resty.redis"
        local red = redis:new()
        red:set_timeout(500000) -- ms
        ok, err = red:connect("192.168.1.8", 6379)
        if not ok then
            ngx.say("failed to connect redis: ", err)
        end
        -- ngx.sleep(3) -- tcp status : ESTABLISHED
        local ok, err = red:set_keepalive(1000000, 10) -- tcp status : TIME_WAIT
        if not ok then
            ngx.log(ngx.ERR, "set keep alive error", err);
            ngx.say("failed to set keepalive: ", err);
        end
    }
}
```

I did not change anything but the redis server IP.

**Comment by agentzh** [comment]
@rupamkhaitan I think you should check whether you configured the `timeout N` directive in your `redis.conf` file for your redis server. Make sure `N` is big enough (or 0 for holding the client connection forever). See

http://download.redis.io/redis-stable/redis.conf

and also

https://redis.io/topics/clients#client-timeouts

I don't really want to support how to configure the redis server, seriously :)

**Comment by rupamkhaitan** [comment]
Great bro, I am so sorry.. I realized that timeout was 5 seconds in my redis.conf (i am so stupid seriously, i thought like nginx default timeout redis will also have 60 seconds)

**Comment by rupamkhaitan** [comment]
Please close this ticket

**Comment by vento-vt** [comment]
@agentzh many thanks about redis info
Find out that if timeout didn't defiend directly in redis.conf - Redis close connections after some time, maybe 10-20 seconds.
Helped to me set "timeout 0" in redis.conf.

P.S. Using lua-resty-redis, lua-resty-redis-connector (to connect by sentinel) and Redis RedHat Docker image
