### ISSUE TITLE
How to overcome the init_by_lua limitation of this library?

### ISSUE THREAD

**Issue by jenia** [openresty/lua-resty-redis#141]
Hello everyone.

What workarounds are available for the problem of not being able to connect to Redis in init_by_lua? 

I see that we can use the socket API to overcome this problem but I'm not totally clear on how to achieve this. Do I need to modify the Redis.lua itself as described here #https://github.com/openresty/lua-nginx-module/issues/206#issuecomment-13041467? 

That's too convoluted in my opinion. Are there other solutions?

Thanks in advance for your kind help.

**Comment by agentzh** [comment]
@jenia Technically speaking, we need to add support for the cosocket API to the `init_by_lua*` context first. Pull requests welcome.

**Comment by agentzh** [comment]
Closing it as it is duplicate with openresty/lua-nginx-module#1020.
