### ISSUE TITLE
The sample of Redis publish may wrong.

### ISSUE THREAD

**Issue by wuxin** [openresty/lua-resty-redis#142]
The sample:
`res, err = red2:publish("dog", "Hello")`
    `if not res then`
`        ngx.say("2: failed to publish: ", err)`
`        return`
`    end`

result of publish() is 0 when its ok.

**Comment by spacewander** [comment]
@wuxin 
In Lua, only `nil` and `failse` make a condition false.

**Comment by wuxin** [comment]
@spacewander 
Thax.
