### ISSUE TITLE
ngx.exit(ngx.HTTP_NOT_FOUND) still returns 200

### ISSUE THREAD

**Issue by scalp42** [openresty/lua-resty-redis#15]
Hi Yichun,

Thanks a lot for all those modules !

I tried to run your example and can't figure how to actually returns a 404 if the key is not found (hence `res == null` in `local res, err = red:get(ngx.var.key_that_does_not_exist)`.

Snippet:

```
    if res == ngx.null then
      ngx.status = ngx.HTTP_NOT_FOUND
      ngx.say("key not found.")
      return ngx.status
    end

    ngx.say("result: ", res)
```

Also tried:

```
    if res == ngx.null then
      ngx.status = ngx.HTTP_NOT_FOUND
      ngx.say("key not found.")
      ngx.exit(ngx.status)
    end

    ngx.say("result: ", res)
```

Output:

```
$> curl -I redis/key_exists
HTTP/1.1 200 OK
Server: ngx_openresty/1.2.7.1
result: "the key exists!"

$> curl -I redis/key_does_not_exist
HTTP/1.1 200 OK
Server: ngx_openresty/1.2.7.1
key not found.
```

Any idea by any chance ?

**Comment by HoldSoulSkip** [comment]
the same  situation happenes to me ,this is a strange thing~

**Comment by agentzh** [comment]
@HoldSoulSkip You must have sent out the request header earlier (maybe implicitly by calling `ngx.print` or `ngx.say` earlier in your code paths). We don't have a time machine so the status code set by a later `ngx.exit()` call cannot take effect. Please ensure you have set `ngx.status = code` before your first response output call.

**Comment by HoldSoulSkip** [comment]
@agentzh Thank you very much ~i will try a soon later~

**Comment by bum** [comment]
You should set response status before "say"
`local function failed(log, err)
	ngx.status = ngx.HTTP_INTERNAL_SERVER_ERROR
	ngx.say(log)
	ngx.log(ngx.ERR, log, err)
	return ngx.exit(ngx.status)
end`
