### ISSUE TITLE
about set_timeout()

### ISSUE THREAD

**Issue by tweyseo** [openresty/lua-resty-redis#155]
i was wrapper this lib and i saw your set_timeout() implement may return nil and err, so i use ok and err to capture the return value, but there return nothing when set_timeout() success...

**Comment by agentzh** [comment]
@tweyseo It does not look like it:

https://github.com/openresty/lua-resty-redis#set_timeout

The documentation for this method does not mention any meaningful return values. What are you referring to?

Sorry for the late reply, BTW.

**Comment by tweyseo** [comment]
i saw it in source code

**Comment by agentzh** [comment]
@tweyseo OK, I see. Just committed a fix to master.
