### ISSUE TITLE
是否可以类似 proxy module 的 keepalive，设置有多少idle的长连接

### ISSUE THREAD

**Issue by jinleileiking** [openresty/lua-resty-redis#157]
压测时，发现如果qps突增，会导致后端连redis的长连接数会突增，这是redis会有异常，半连接数等问题。
能否设置一个值，让其保持N个闲的长连接，类似nginx proxy pass。

--- 后续补英文翻译

**Comment by zyxtomcat** [comment]
*tcpsock:setkeepalive(timeout，size)， size参数就是设置连接池大小的*

jinleileiking <notifications@github.com> 于2019年1月16日周三 下午5:53写道：

**Comment by jinleileiking** [comment]
当前配置如果是 100s， 10000条连接，如果一个连接已经100s了，但连接池还有9000个，这个连接是销毁，还是还给连接池？

**Comment by jinleileiking** [comment]
先关闭。感谢@zyxtomcat
