### ISSUE TITLE
Redis streams command support?

### ISSUE THREAD

**Issue by vstath** [openresty/lua-resty-redis#158]
Hello @agentzh ,

would it be possible to include the new STREAMS commands of Redis v.5? 

https://redis.io/commands#stream 

Since a lot of people use this library and it's included with openresty, it would be ideal if the addition was done by a core developer. I have added XADD command for now (similar code to HMSET) but I'm not sure that's the proper way to do it. 

I am sure the community would appreciate an official support for stream commands. 

Thank you!

**Comment by agentzh** [comment]
@vstath Any new redis commands (including any ones added in the future) are automatically supported by the current library. Thanks to the redis commands' forward compatibility design.
