### ISSUE TITLE
Feature: SSL for in-transit encryption

### ISSUE THREAD

**Issue by SvenAlHamad** [openresty/lua-resty-redis#160]
I was wondering if there is a possibility to add an in-transit encryption support, like the one you can find in Redsmin and few other redis clients. (https://redislabs.com/blog/secure-redis-ssl-added-to-redsmin-and-clients/)

Similar to the above, Amazon AWS Elasticache has the same feature and if it's enabled you can't use this library to connect to your redis instance as it doesn't support this mechanism: 
![image](https://user-images.githubusercontent.com/3808420/51764746-d5de2200-20cd-11e9-93d1-e9255067de40.png)

Regards

**Comment by agentzh** [comment]
Yeah, it's on our TODO list.

**Comment by jianchen2580** [comment]
hey, any updates for redis SSL(in-transit encryption)?

**Comment by linhdangduy** [comment]
+1

**Comment by vinayakhulawale** [comment]
I submitted PR for this - https://github.com/openresty/lua-resty-redis/pull/168

**Comment by vinayakhulawale** [comment]
@agentzh - will you able to review #168 ?

**Comment by thibaultcha** [comment]
SSL support has been merged from #168 to the master branch in 79d24214095c921b879319e512b2f20fddf0795e! It will be part of the upcoming 1.17.x.1 release. Thank you @vinayakhulawale.

**Comment by olegburov** [comment]
@thibaultcha do you have an ETA when `v1.17.x.1` will come out?
