### ISSUE TITLE
how to use `sort` command?

### ISSUE THREAD

**Issue by Azleal** [openresty/lua-resty-redis#164]
I was trying to use the `sort` command on a set.
in redis-cli I can use `sort key-name alpha limit 0 5` to get the first 5 sorted elements. now the question is: how could I use this `sort` command with lua-resty-redis?
I've tried: `red:sort("key-name", "alpha")`, `red:sort("key-name alpha")`  in lua script, however it didn't work. so if anyone please tell me how to use this command, thank you every much~

**Comment by Azleal** [comment]
Ok, after more than I don't know how many times try, I finally get the correct result. here is the code:
`redis:sort("key-name", "limit", 0,5, "alpha")`

**Comment by agentzh** [comment]
@Azleal Always read the redis official command doc for usage:

https://redis.io/commands/SORT

This library does not do anything specifically with most of the commands like `sort` anyway.

**Comment by agentzh** [comment]
@Azleal If this library does anything special about a redis command, it is always documented in the README.
