### ISSUE TITLE
How can i get redis “config get  databases” command

### ISSUE THREAD

**Issue by lifeblood** [openresty/lua-resty-redis#181]

**Comment by agentzh** [comment]
@lifeblood Maybe `red:config("get", "...")`? Note that all redis commands (both old and new) can be mapped to the Lua method call this way.

**Comment by lifeblood** [comment]
thank you, Ask another question
what command  can get all redis key with  ofset and limit

**Comment by agentzh** [comment]
@lifeblood Please read the redis official documentation like this:

https://redis.io/commands

We do support all of them.

**Comment by agentzh** [comment]
@lifeblood Also, general questions should be asked on the openresty mailing lists:

http://openresty.org/en/community.html

This place is for bug report and patch discussion only. Thanks for your understanding.
