### ISSUE TITLE
Redis 500 internal error

### ISSUE THREAD

**Issue by javierlga** [openresty/lua-resty-redis#184]
Hello,

Our websites have been randomly receiving this error `/etc/nginx/lua/cache_update.lua:137: in main chunk, client: x.x.x.x, server: _, request: "GET / HTTP/1.1", host: "www.xxxx.com"`  that causes  a `500 Internal Server Error` in the website. 

Here is the connection code:

```
local redis_connection_timeout = 100             
function connect_redis(red, host, auth)
  local redis_host = assert(host, "no redis host")
  local redis_port = 6379

  red:set_timeout(redis_connect_timeout)

  local ok, err = red:connect(redis_host, redis_port)

  if not ok then
    print("Redis connection error while connecting to redis: ", err)
    return false, err
  end
  return ok, err
end
``` 

Cache_update.lua code (line 137 calls the **run()** function):

```
...
some code here
...

function run()
  local update_skip = tonumber(ngx.var.cache_update_skip or "0")
  local skip_header = ngx.var.cache_skip_header or "X-Skip-Fetch"
  local header_skip = ngx.var["http_" .. skip_header:lower():gsub("-", "_")]

  -- Bail if skip header
  if header_skip or update_skip == 1 then return end

  local ttl = ttl(cache_key)

  -- Key is fresh, no action needed
  if ttl > stale_time then return end

  local cache_methods = ngx.var.cache_methods or "GET"
  local method = ngx.var.request_method

  -- Bail if method not cached
  if not cache_methods:find(method) then return end

  -- local fullurl = ngx.var.scheme .. "://" .. ngx.var.server_addr .. ":" .. ngx.var.server_port .. ngx.var.request_uri
  -- Use loopback
  local fullurl = "http://127.0.0.1:" .. ngx.var.server_port .. ngx.var.request_uri
  local lock_key = "cache.lock/" .. cache_key

  if ttl == -2 then
    -- expired
    -- sync request
    miss_request(http, fullurl, method, ngx.req.get_headers(), ngx.req.get_body_data(), skip_header, lock_key)
  else
    -- just stale
    -- async request to update cache
    update_cache(http, fullurl, method, ngx.req.get_headers(), ngx.req.get_body_data(), skip_header, lock_key, ttl)
  end
end

run()
```

I'm not completely sure what's going on since our ElasticCache redis instance is running with no issues, no high CPU or memory usage.   

**Environment**:
OpenResty version: 1.15.8.2 
Kubernetes version: 1.15.3
OS image: Debian GNU/Linux 9 (stretch)

Any help is really appreciated.

**Comment by agentzh** [comment]
@javierlga Every time you see a 500 error page, you should really check out your nginx's error log file for details.

**Comment by javierlga** [comment]
> @javierlga Every time you see a 500 error page, you should always check out your nginx's error log file for details.

Yes, I know, we're using Datadog agent deployed as a `DaemonSet` that collect the logs from all the containers in the cluster, this our directive in nginx:
`error_log  /dev/stdout;`

**Comment by agentzh** [comment]
@javierlga Just check the error log messages corresponding to those 500 responses. It doesn't matter how you generate and collect your nginx error log data.

**Comment by javierlga** [comment]
Here are other errors:
```
2020/02/11 06:09:21 [error] 40#40: *91021 lua entry thread aborted: runtime error: /etc/nginx/lua/redis_connect.lua:11: bad request
```

**Comment by agentzh** [comment]
@javierlga This error is documented in the official documentation in detail. It's your Lua code's usage mistake. Never share cosocket objects across different requests! They surely will have access conflicts.
