### ISSUE TITLE
error connection to redis unix socket

### ISSUE THREAD

**Issue by davidka79** [openresty/lua-resty-redis#187]
Hello
I would like to use only unix socket for redis connect, but when I try to do simple connection as in examples, I getting error:

2020/03/09 09:59:57 [error] 1878#1878: *18 lua entry thread aborted: runtime error: /opt/nginx/lualib/resty/redis.lua:141: bad argument #2 to 'connect' (number expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'connect'
        /opt/nginx/lualib/resty/redis.lua:141: in function 'connect'
        /opt/nginx/lualib/init.lua:29: in function </opt/pop/lualib/init.lua:23>, context: ngx.timer, client: 185.40.72.110, server: 0.0.0.0:443
2020/03/09 09:59:57 [error] 1878#1878: *19 lua entry thread aborted: runtime error: /opt/nginx/lualib/resty/redis.lua:141: bad argument #2 to 'connect' (number expected, got nil)

and my code is
in init_by_lua
--# LOGGING FUNCTION
function putLog(premature, customer)

  -- redis connect
  local redis = require "resty.redis"
  local red = redis:new()
  red:set_timeouts(1000, 1000, 1000)
  local ok, err = red:connect("unix:/var/run/redis/redis.sock")

  -- DB INSERT
  red:select(0)
  red:hincrby(customer, 'count', 1)

  -- end, release connection back to pool
  local ok, err = red:set_keepalive(10000, 100)
  if not ok then
      ngx.log(NGX.ERR, "failed to set keepalive: ", err)
      return
  end
end

log_by_lua_block {
  local customer = tonumber(ngx.var.customer) or 0
  local ok, err = ngx.timer.at(1, putLog, customer)
  if not ok then
    ngx.log(ngx.ERR, "ERROR from the CODE: failed to create timer: ", err)
  end
}

OS:
Ubuntu Server 18.04.4
redis socket location:
/var/run/redis/redis.sock
srwxrw-rw-  1 redis redis   0 Feb 29 18:54 redis.sock

redis-cli and goland apps can connect to socket, I mean socket is present

Thank you 
ADD:
If I use IP:Port instead of socket, everything is fine

UPD:
It does not mater socket is present or not, I getting this error even if I put wrong path to connection string :(

**Comment by walter0909** [comment]
when i use network config is true, use socket is false

**Comment by doujiang24** [comment]
@davidka79 
your sample should work according to the doc:
https://github.com/openresty/lua-resty-redis#connect

are you sure there is no other mistakes like a typo in your code?

**Comment by bjoe2k4** [comment]
@doujiang24 Unfortunately, 79d24214095c921b879319e512b2f20fddf0795e introduced a bug, which broke `red:connect('unix:/some/redis.sock')`. 
Sadly, none of the tests covers this. Tests 2&3 in `bugs.t` have the unix socket version commented out. I suggest to explicitly test this.

The connect method of a TCP socket `sock = ngx.socket.tcp()` does not accept `nil` as a second argument. Only the third argument may be `nil`.

**Comment by osmanmakal** [comment]
```
bad argument #2 port: number expected, got nil
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/usr/local/openresty/lualib/resty/redis.lua:122: in function 'connect'
```
unix socket connection problem continues .. @bjoe2k4

**Comment by bjoe2k4** [comment]
Have you tried my fix from the pull request? Waiting for my pull to be merged may take a while.

Unfortunately openresty devs are super busy these days and development (at least the public opensource part) is sometimes stalled for weeks, months and years. Nevertheless the openresty platform is one of the most stable platforms i have ever encountered and i am more than grateful to what i have learned by using it.

Also there is https://github.com/openresty/lua-nginx-module/pull/1735 going on, which will likely require some changes on my side.

**Comment by broxio** [comment]
use latest from current repo , problem still persist.

2022/04/27 14:25:39 [error] 292750#0: *3 lua entry thread aborted: runtime error: content_by_lua(zzz.conf:24):7: bad argument #2 opts: nil or table expected, got string
stack traceback:
coroutine 0:
        [C]: in function 'error'
        /opt/lua53/lib/resty/redis.lua:128: in function 'connect'
        content_by_lua(zzz.conf:24):7: in function <content_by_lua(zzz.conf:24):1>, client: 10.7.7.7, server: , request: "GET /t HTTP/1.1", host: "10.7.7.77:80"
