### ISSUE TITLE
Pub/sub bug on multi subscribe?

### ISSUE THREAD

**Issue by vstath** [openresty/lua-resty-redis#193]
Hello, 

perhaps I'm misusing the lua-resty-redis but I have a repeatable problem when I try to subscribe sequentially to multiple redis channels as needed. 

The "subscribe" command of Redis allows one to do something like

"subscribe channelname" 

Once the client enters the subscribed state it is not supposed to issue any other commands, except for additional SUBSCRIBE, PSUBSCRIBE, UNSUBSCRIBE, PUNSUBSCRIBE, PING and QUIT commands.

So my flow is

subscribe control-channel
<various code>
subscribe channel-1
<various code>
subscribe channel-2

Although this works fine when doing direct telnet to redis, I get unpredictable results when using lua-resty-redis. The response some times is the actual Redis protocol. I have a simple command line example that demonstrates the issue. 

File "red_sub.lua"

```
local redis = require "resty.redis"
-- local cjson = require "cjson"
local red = redis:new()

local ok, err = red:connect("127.0.0.1", 6379)

if err then
    print("Failed: " .. err)
end

if ok then
    local sub, sub_err = red:subscribe("control")

    while true do
        local res, err = red:read_reply()

        -- ngx.say(cjson.encode(res))

        red:subscribe(res[3])
    end
end
```

runs with "resty red_sub.lua"

Afterwards you need to run the next file

File "red_pub.lua"

```
local redis = require "resty.redis"
-- local cjson = require "cjson"
local red = redis:new()

local ok, err = red:connect("127.0.0.1", 6379)

if err then
    print("Failed: " .. err)
end

if ok then
    local i = 1

    while i <= 20 do
        local res, err = red:publish("control", "ch-" .. i)
        i = i + 1
    end
end
```

runs with "resty red_pub.lua" after the "red_sub.lua" has started.

Then if you do "redis-cli MONITOR" you can see that some requests are "subscribe ch-[1..20]" but some are not and if you print the result of red:read_reply() you will see that the RESP (redis protocol) is returned :-(

Thank you for your excellent software and I hope some experienced developer can check if this is a bug in the library?

**Comment by vstath** [comment]
Sample result from red_sub.lua (see lines such as ``["subscribe","ch-10",11]`` which is the Redis protocol response:

```
["message","control","ch-1"]
["subscribe","ch-1",2]
["message","control","ch-3"]
["message","control","ch-4"]
["message","control","ch-5"]
["message","control","ch-6"]
["message","control","ch-7"]
["message","control","ch-8"]
["message","control","ch-9"]
["message","control","ch-10"]
["subscribe","ch-10",11]
["subscribe","11",12]
["subscribe","12",13]
["message","control","ch-14"]
["message","control","ch-15"]
["subscribe","ch-15",16]
["subscribe","16",17]
["message","control","ch-18"]
["message","control","ch-19"]
["message","control","ch-20"]
```

**Comment by doujiang24** [comment]
@vstath seems weird, we will take a look at it soon.

**Comment by spacewander** [comment]
Currently lua-resty-redis uses ping-pong model to handle redis protocol, which is incorrect if you mix pub/sub with other commands including `subscribe`. Only safe commands to use after `subscribe` are `read_reply` and `unsubscribe`. You need to use a new redis client to do new subscription.

**Comment by xlibor** [comment]
@vstath I can reproduce your situation in my local environment. It can be avoided in several ways: 

1. Use a new redis instance to subscribe new channels;
2. After publishing one message, pause for a while(such as `ngx.sleep(0.001)`) to avoid sending the message too fast;

**Comment by vstath** [comment]
@doujiang24 thank you
@spacewander I appreciate it but it's not possible to create a new redis client per new subscription, unfortunately
@xlibor thank you, I have seen that as an option but it is not optimal and hides the actual problem (in other words it may backfire)

I will try to think of other ways to do what my code in the example needs using timers and shared dictionaries perhaps. 

Since we are on the topic, are there plans to update lua-resty-redis in the future? Redis 6 (GA will be by the end of the month) will have local caching among other features. This means that RESP 3 protocol needs to be adopted and use of shm (I assume). 

Are there any plans to support Redis 6 in the future (which can have an approximation of time, not a general "yes")? Unfortunately I cannot contribute code (that makes sense to use) but I can help in other, peripheral, things that you can instruct me to help. 

The openresty / lua / redis stack is a very strong combination of technologies, in my opinion. What can I do to contribute towards supporting Redis 6 and fix the subscribe issue? Do we / should we have bounties in order for knowledgeable people to work towards such tasks?

**Comment by vstath** [comment]
Info on Redis 6 client side caching: https://redis.io/topics/client-side-caching for those who are not familiar with it.

**Comment by vstath** [comment]
@xlibor I believe the ngx.sleep(x) does not work either because if you unsubscribe from a channel you have to reconnect to redis if you want to subscribe again to the same channel. Not sure if it's related to ticket #145

**Comment by spacewander** [comment]
@vstath 
https://github.com/openresty/lua-resty-redis/pull/195 may have fix your problem in some levels.
The `unsubcribe` is still broken and we will fix it in the next PR.

**Comment by vstath** [comment]
@spacewander indeed, that fixed the original problem, indeed. Thank you for it and your work in openresty (and your RSA resty module) ;-)

**Comment by vstath** [comment]
@spacewander I can't thank you enough!
