### ISSUE TITLE
Error invalid size ""

### ISSUE THREAD

**Issue by lucas1** [openresty/lua-resty-redis#199]
See error: 

invalid size ""

stack traceback:
coroutine 0:
	[C]: in function 'send'
	/usr/local/openresty/lualib/resty/redis.lua:255: in function 'get'

**Comment by spacewander** [comment]
Need a minimal reproducible example to reproduce the issue. And what's your OpenResty and lua-resty-redis's version?

**Comment by lucas1** [comment]
local resty_sha256 = require "resty.sha256"
local str = require "resty.string"
local sha256 = resty_sha256:new()
sha256:update(ngx.var.http_host .. ngx.var.request)
local digest = sha256:final()
local key = str.to_hex(digest)
local data, _ = red:get(key)

I'm using this script:
https://blog.donatas.net/blog/2017/07/25/limit-bandwidth-openresty/

**Comment by spacewander** [comment]
Is the `key` variable empty?
The `send` method from `ngx.socket.tcp` doesn't throw an error with `invalid size ""`, what version do you use? Do you use a modified version of lua-nginx-module?

**Comment by lucas1** [comment]
libluajit-5.1.so.2 => /usr/local/openresty/luajit/lib/libluajit-5.1.so.2 (0x00007f0498012000)

**Comment by lucas1** [comment]
I added:
ngx.log(ngx.ERR, "ERROR:" .. key)

2020/05/25 02:17:11 [error] 17807#17807: *30164688 invalid size "", client: 37.175.37.248, server: , request: "GET file.mp4 HTTP/2.0", host: "ibyonafgqk.mstreamcdn.com", referrer: "https://mstream.fun/zvr8drknt5ah"
2020/05/25 02:17:11 [error] 17807#17807: *30164688 [lua] functions.lua:69: request_count(): ERROR:a5c333ae41b1f9d8b392ce1f747aa85e482473fc1b716d7bcd0d2dedee9433e0, client: 37.175.37.248, server: , request: "GET file.mp4 HTTP/2.0", host: "ibyonafgqk.mstreamcdn.com", referrer: "https://mstream.fun/zvr8drknt5ah"

**Comment by lucas1** [comment]
I added log:
ngx.log(ngx.ERR, "ERROR:" .. key)

2020/05/25 02:17:11 [error] 17807#17807: *30164688 invalid size "", client: 37.175.37.248, server: , request: "GET /9LUWE8vuBOE3uW1bVulfEhDhNMfwzwescBry7ph5HU8.mp4 HTTP/2.0", host: "ibyonafgqk.com", referrer: "https://fun/zvr8drknt5ah"
2020/05/25 02:17:11 [error] 17807#17807: *30164688 [lua] functions.lua:69: request_count(): ERROR:a5c333ae41b1f9d8b392ce1f747aa85e482473fc1b716d7bcd0d2dedee9433e0, client: 37.175.37.248, server: , request: "GET /9LUWE8vuBOE3uW1bVulfEhDhNMfwzwescBry7ph5HU8.mp4 HTTP/2.0", host: "ibyonafgqk.com", referrer: "https://fun/zvr8drknt5ah"

**Comment by lucas1** [comment]
See other error:
[error] 6989#6989: *31465717 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/resty/redis.lua:255: bad request

**Comment by lucas1** [comment]
I updated resty-redis current, see error:
2020/05/26 02:34:12 [error] 11088#11088: *31535332 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/resty/redis.lua:335: bad request
stack traceback:
coroutine 0:
	[C]: in function 'send'
	/usr/local/openresty/lualib/resty/redis.lua:335: in function 'get'

**Comment by lucas1** [comment]
Solved disable error_log and solved error in script that call method request_count twice. After this stopped errors.
