### ISSUE TITLE
Redis Connection error ....connect() failed (111: Connection refused), client: 172.17.0.1, server: 

### ISSUE THREAD

**Issue by Sargababu** [openresty/lua-resty-redis#201]
Hi , I have redis and nginx running containers locally. When I try to connect to redis from my nginx i get connection error. There was alot of similar issue reported online but even trying out those option didnt work for me.

Redis is accessible from my local host throught redis-cli -127.0.0.1 -p 6379 

But when i try to connect from my nginx lua script ,It refuses connection.

```
connect() failed (111: Connection refused), client: 172.17.0.1, server: , request: "POST /riverainct/ HTTP/1.1", host: "127.0.0.1:8080"
2020/06/10 16:31:10 [error] 6#6: *1 [lua] service-execute.lua:27: failed to connect: connection refused, client: 172.17.0.1, server: , request: "POST /riverainct/ HTTP/1.1", host: "127.0.0.1:8080"

```

 My lua code is as below

```
local redis = require "resty.redis"
local options_table = {}
options_table["pool"] = "docker_server"
local red = redis:new()
red:set_timeout(100000)
local ok, err = red:connect("127.0.0.1", 6379, options_table)
if not ok then
    ngx.log(ngx.ERR, "failed to connect: "..err)
    ngx.exit(500)
end

```
Also tried running redis using custom redis config setting 
bind 127.0.0.1
and turned off protectionmode

Could this be nginx config issue?
below is my nginx config content

```
server {
        listen 8080;
        #sample get url
        # download
        autoindex_exact_size on;   # output file sizes rounded to kilobytes, megabytes, and gigabytes
        autoindex_localtime on;     # output local times in the directory

        client_max_body_size 480000M;
        set $inputpath /upload/input/;
        set $outputpath /upload/output/;
        location  /<seviceendpoint>/ {
            access_by_lua_file /etc/nginx/lua/service-execute.lua;
            proxy_pass <external ip address to route the call to>;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }

```

I have nothing specific for redis in nginx config file. When the service endpoint is called i need to add some entires to redis db and then route the call to an external service . This is what I am trying to acheive.

**Comment by mickys** [comment]
My best guess would be your firewall. Had something similar happen on a CentOS 8 install recently. Turn it all off and see if that does it for you.

**Comment by ryanf5** [comment]
This relates to docker networking, either use `172.17.0.1` or setup shared named network and reference using `aliases`, you may need to add `resolver` in your `nginx.conf` to use `127.0.0.11` as its docker default resolver
