### ISSUE TITLE
How to implement redis set collection limit

### ISSUE THREAD

**Issue by jclivi** [openresty/lua-resty-redis#202]
How to implement redis set collection limit

redis:sort(name):limit(0, 1)

**Comment by rainingmaster** [comment]
@jclivi 
You can try like this: `redis:sort(name, "limit", 0, 1, "desc")`

**Comment by jclivi** [comment]
> @jclivi
> 您可以这样尝试：`redis:sort(name, "limit", 0, 1, "desc")`

Thank you

**Comment by jclivi** [comment]
@rainingmaster 
Thank you

**Comment by rainingmaster** [comment]
Also you can refer this form: https://forum.openresty.us/
