### ISSUE TITLE
why not close sock when sock:receive(2) failed at _read_reply()

### ISSUE THREAD

**Issue by stone-wind** [openresty/lua-resty-redis#207]
local dummy, err = sock:receive(2) -- ignore CRLF
        if not dummy then
            return nil, err
        end

**Comment by doujiang24** [comment]
@stone-wind 
I think it should be removed by accident in this commit: https://github.com/openresty/lua-resty-redis/commit/d9025fdf3c3fe4a0c50474e83e4f2c58506933a2#diff-adb515948c05651051c83fd6fb3ce7ceL173

Will you help to create a PR to fix it? Thanks :)
