### ISSUE TITLE
How to configurate database 1?

### ISSUE THREAD

**Issue by snpcp** [openresty/lua-resty-redis#212]
How to configurate database 1? Do I have to use 'SELECT 1' before every call to 'GET'? look forward to your reply.

**Comment by qiankunxienb** [comment]
local oke, err = redis_instance:select(10)   # choose db 10

**Comment by dragon-zhang** [comment]
> How to configurate database 1? Do I have to use 'SELECT 1' before every call to 'GET'? look forward to your reply.

No need ?

**Comment by monkeyzhu333** [comment]
Default the `resty.redis`  database is `0`
You can use `red1:select(1)`  to change database .

for example:
```local redis1 = require "resty.redis"
local red1 = redis1:new()
local ok1, err = red1:connect("192.168.1.234",6379)
if not ok1 then
    ngx.log(ngx.ERR,"key: ", err)
    return
end

red1:select(1)

Note if you don't use the `red1:select(1)`  ，`set_keepalive` will  change the defaut database ;because of old connection is reused

**Comment by snpcp** [comment]
ok, thanks for your reply. this will help me.😁
