### ISSUE TITLE
Internal Server Error when connect via UNIX socket

### ISSUE THREAD

**Issue by sdmrnv** [openresty/lua-resty-redis#216]
Hello!

After upgrading OpenResty up to 1.17 (from 1.15) Internal Server Error is appears when trying to connect to Redis via unix socket. When connect via ip+port all OK.

**Comment by spacewander** [comment]
Related commit: https://github.com/openresty/lua-resty-redis/commit/5ea766adbacbff0b5cf32ebb28612f553059223f?

**Comment by sdmrnv** [comment]
> Related commit: [5ea766a](https://github.com/openresty/lua-resty-redis/commit/5ea766adbacbff0b5cf32ebb28612f553059223f)?

Yes. Thanks!

**Comment by spacewander** [comment]
Solved.
