### ISSUE TITLE
smembers usage

### ISSUE THREAD

**Issue by oneslideicywater** [openresty/lua-resty-redis#223]
I notice the code [here](https://github.com/openresty/lua-resty-redis/blob/0244f0931b71b2cd9fba7dab2549792d1ae71ec6/lib/resty/redis.lua#L33) have all related redis commands,but I can't see corresponding method in this file. 

I try to use this library like this,but it always return nil.
```lua 
 route_keys, err = red:smembers("routes")
    if not route then
        ngx.log(ngx.ERR,"failed to get routes: ", err)
        return
    end

```

does this library support the `smembers`  and if not, how can I extense it ?

**Comment by toredash** [comment]
Have you tried running that command with the redis client ? `smembers` should be supported so I assume this is a user error

**Comment by oneslideicywater** [comment]
sorry about that.  I can't see corresponding method in this file,so it's [this line](https://github.com/openresty/lua-resty-redis/blob/0244f0931b71b2cd9fba7dab2549792d1ae71ec6/lib/resty/redis.lua#L449) taking effect  when so many support redis cli command

**Comment by toredash** [comment]
It's on this line: https://github.com/openresty/lua-resty-redis/blob/0244f0931b71b2cd9fba7dab2549792d1ae71ec6/lib/resty/redis.lua#L40
