### ISSUE TITLE
Mixed responses in SSI

### ISSUE THREAD

**Issue by aotd1** [openresty/lua-resty-redis#23]
I have page with SSI includes,

``` html
 <!--# include /widget/user/1 -->
 <!--# include /widget/advert/37884 -->
```

Problem is nginx randomly mixes ssi content, so in user-block you can see advert and user info in advertisement block =)

ssi catches by location

``` nginx
location /widget/ {
    internal;
    lua_code_cache off;
    content_by_lua_file '/etc/nginx/lua/widget_redis.lua';
    error_page 404 502 500 503 = @generate-widget;
}
```

``` lua
redis = require "resty.redis"
red = redis:new()
red:set_timeout(500)

ok, err = red:connect("127.0.0.1", 6379)
if not ok then
    ngx.log(ngx.ERR, "Connection error")
    ngx.exit(ngx.HTTP_SERVICE_UNAVAILABLE)
    return
end

content, err = red:get(ngx.var.uri .. "/")
if not content then
    ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
    return
end

if content == ngx.null then
    ngx.exit(ngx.HTTP_NOT_FOUND)
    return
end

ngx.header["Content-Type"] = "text/html; charset=utf-8"
ngx.print(content)
```

If Redis-key `/widget/user/1/` exists, lua prints it contents.
Else @generate-widget (php-fpm) render and store it in redis. 
All is ok when all widgets rendered by @generate-widget, but when some widgets already stored in redis (and other slowly generated by php) they appears in first ssi blocks.

How can I fix it?

**Comment by 6api** [comment]
could you please give me some example for lua + ssi?

**Comment by taf2** [comment]
sure here's an example:

```
set $a '';
set $b '';
set $view '';

rewrite_by_lua '
   ngx.var.a = 'hello' -- pulled value from database

   -- control logic here to select a view
   ngx.var.view = 'my.html'
';
try_files /$view /404.html;
```

my.html
```
<h1>Hello <!--# echo var="b" encoding="none" default="" --></h1>
<p><!--# echo var="a" encoding="none" default="" --></p>
```

it's kind of nice right, you can add control flow in the lua rewrite block to select a different html file and you can inject variables into that html file or js file based on maybe sql queries or redis commands... 

In away it's like using ssi as your templating engine... a little verbose compared to maybe mustache or erb but kind of easy to stitch together pages...

**Comment by r-omk** [comment]
I have the same "randomly mixes ssi content"  with  content_by_lua_file, but if I using  
attribute "wait".

`<!--# include virtual="/path_with_lua" wait="yes" -->`

then it seems everything works as it should.

Can I safely use it with attribute "wait" or completely avoid using lua with ssi?

**Comment by agentzh** [comment]
@r-omk That might be just a happy accident. These two models cannot reconcile per se. Well, you are free to use whatever that appears to work; I just cannot give you any guarantees :)
