### ISSUE TITLE
Connect failed when using hostname instead of IP address

### ISSUE THREAD

**Issue by czf0613** [openresty/lua-resty-redis#240]
I see the document says you can connect to redis using "red:connect("127.0.0.1", 6379)", but I found something wrong when I use the host name instead of IP address.
For example, I bought the redis server from the cloud service, they provided me a connection address "my.redis.aliyuncs.com". But it has an error when I use "**red:connect("my.redis.aliyuncs.com", 6379)**". Is there something wrong with DNS? Or, I just made a mistake? I am pretty sure that I can connect successfully by using other redis desktop manager.

I am looking forward to your reply. Thanks sincerely!

**Comment by zhuizhuhaomeng** [comment]
is there any error log?

**Comment by czf0613** [comment]
> 
No any, it just shows that failed to connect to "my.redis.aliyuncs.com".
It's quite weird.

**Comment by zhuizhuhaomeng** [comment]
can you post your nginx.conf, so we can reproduce this problem

**Comment by czf0613** [comment]
> 

Sure, please view the nginx configuration file in: https://czf-net.xyz/res/nginx.conf
The lua script is also included at: https://czf-net.xyz/res/access_control.lua
Thanks for your great help!

**Comment by ryanwohara** [comment]
I am facing this error while using Kong. Is there any additional information I would be able to provide?

**Comment by zhuizhuhaomeng** [comment]
@czf0613 you need to specify a resolver. eg
resolver 4.4.4.4 ipv6=off;

**Comment by zhuizhuhaomeng** [comment]
http://nginx.org/en/docs/http/ngx_http_core_module.html#resolver

**Comment by czf0613** [comment]
It does not work at all...
But I tried another case, I add a TCP proxy in openresty like this:

stream {
    server {
        listen 30003;
        proxy_pass r-8vbiib2him1kzqtbhf.redis.zhangbei.rds.aliyuncs.com:6379;
    }
}

This piece of code works no matter whether you specify the resolver or not, which means the default DNS resolver in my server is correct.
I think it may still has some bugs in the lua-resty-redis.
Thanks for your regard.

> @czf0613 you need to specify a resolver. eg resolver 4.4.4.4 ipv6=off;

**Comment by ryanwohara** [comment]
I agree with @czf0613 that there is a DNS bug here. My resolver is declared properly in /etc/resolv.conf - I shouldn't need to specify it elsewhere.

**Comment by zhuizhuhaomeng** [comment]
modified the lua code, and got the following error
2021/12/26 18:46:24 [error] 986#986: *6 [lua] access_control.lua:14: redis connection failed!no resolver defined to resolve "r-8vbiib2him1kzqtbhf.redis.zhangbei.rds.aliyuncs.com", client: 127.0.0.1, server: pic-bed.xyz, request: "GET /service HTTP/1.1", host: "127.0.0.1"


```
local redis_pack = require "resty.redis"
local redis = redis_pack:new()

redis:set_timeouts(1000, 1000, 1000)

-- writing connection address in this way is OK
-- local ok, err = redis:connect("10.0.0.205", 6379)

-- but failed in this way, I was wondering if there is any problem in DNS? 
local ok, err = redis:connect("r-8vbiib2him1kzqtbhf.redis.zhangbei.rds.aliyuncs.com", 6379)

if not ok then
    ngx.log(ngx.ERR, "redis connection failed!", err)
    ngx.exit(502)
    return
end
```

**Comment by czf0613** [comment]
> 

It still shows that 'no resolver defined to resolve "r-8vbiib2him1kzqtbhf.redis.zhangbei.rds.aliyuncs.com", client: 58.63.62.105, server: , request: "GET /res HTTP/1.1"'

**Comment by ryanwohara** [comment]
@czf0613 Did you find a solution? Why did you close this?

**Comment by czf0613** [comment]
> 

Quite weird, I asked my cloud service provider and they gave me a DNS server. I configured my docker DNS resolver, and, it works. I cannot understand why...... 
I believe that it must be some problems in DNS, maybe some bugs in nginx, not the lua-resty-redis.

**Comment by ryanwohara** [comment]
Thanks for the insight, appreciated

**Comment by mpdafa** [comment]
@czf0613 hi it must be quite a while
but here i am facing same issue as well where i use this module for our KONG plugin
may i know what is your cloud provider?

> Quite weird, I asked my cloud service provider and they gave me a DNS server. I configured my docker DNS resolver, and, it works.

**Comment by czf0613** [comment]
It's not related to the cloud provider, configure a valid DNS via docker or the nginx.conf can solve this problem.

**Comment by mpdafa** [comment]
sure then, seems kinda similiar to my root cause
update : just did resolve this by adding this additonal module just to resolve the dns & return IP and it works! seems my previous module somehow can't interact to nameserver (in resolv.conf) properly

```
local resolver = require "resty.dns.resolver"
      r, resolve_err = resolver:new{
          nameservers = nameservers,
          retrans = 2,  -- number of retransmissions
          timeout = 2000,  -- timeout in milliseconds
      }
answers, query_err = r:query(hostname, {qtype = r.TYPE_A})
```

context : the dns is used for redis
