### ISSUE TITLE
lua entry thread aborted: runtime error: /usr/local/openresty/lualib/resty/redis.lua:158: bad request

### ISSUE THREAD

**Issue by navysummer** [openresty/lua-resty-redis#249]
![image](https://user-images.githubusercontent.com/17807236/167286339-63cf80f8-4b85-47b3-a071-2000131ccda5.png)

![image](https://user-images.githubusercontent.com/17807236/167286381-7a3a9c10-906f-431a-85b2-30d1126e36ef.png)
``

**Comment by RocFang** [comment]
Just create a new resty.redis object on every request, never share it  across your Lua requests.

**Comment by navysummer** [comment]
> 

thanks
