### ISSUE TITLE
Connect to redis using upstream

### ISSUE THREAD

**Issue by eoranged** [openresty/lua-resty-redis#25]
**Intro**

Now we are using `http_redis2_module` and load-balancing read-only connections to the redis cluster with `http_upstream_module`. But It's annoying to write tons of locations for each kind of request, so we are thinking about migration to `lua-resty-redis` or another Lua-based redis client, but I am sure that It is not good idea to re-implement load-balancing (including work with failed servers in upstream) in pure Lua.

**The question**

So, Is it possible to use the library to connect to Redis using upstreams?

**Comment by wonderbeyond** [comment]
Any existing code for reference? whether lua or not.

**Comment by wonderbeyond** [comment]
I've done a very basic redis load balancer module: https://gist.github.com/wonderbeyond/11a20570bb5b1b1bf818bf03e527faf6

I just select the next server from a given list circularly.

**Comment by marius-c** [comment]
hmm is the above example correct ? is that counter shared across all workers / sessions ?

**Comment by wonderbeyond** [comment]
I  have used it in production until now.

The counter is shared in one single worker.

**Comment by marius-c** [comment]
yep makes sense. just read the docs. thanks for sharing.

**Comment by wonderbeyond** [comment]
However, I think we need  a more powerful balancer module.
e.g. We can report failure of one redis node to the balancer, the balancer will not select it for a period of time.

Are you interesting?
