### ISSUE TITLE
Redis connection issues

### ISSUE THREAD

**Issue by urosgruber** [openresty/lua-resty-redis#27]
Hi,

I'm doing some redis lookups in my lua script and I'm getting some weird connection problems which I don't know how to properly debug to actually get to the source of the problem.

Here is snip from config

```lua
- Connect to Redis
local redis = require "resty.redis"
local red = redis:new()

red:set_timeout(1000)
local ok, err = red:connect("127.0.0.1", 6379)

if not ok then
    ngx.log(ngx.ERR, "Redis connection failure: " .. err)
    return
end
    
- rest of the code ...

```

On a random basis I get a lot of  **Redis connection failure: timeout** in nginx error log. While debug loging redis server I don't see any connections at that same moment. 

I'm using latest lua-resty-redis and 0.8.6 ngx_lua module. I also try to upgrade to 0.9.2 but then I get even more strange errors

```
2013/11/10 23:24:53 [error] 52514#0: *15 attempt to send data on a closed socket: u:0000000000000000, c:0000000000000000, ft:0 eof:0, 
2013/11/10 23:24:53 [error] 52514#0: *15 attempt to send data on a closed socket: u:0000000000000000, c:0000000000000000, ft:0 eof:0, 
2013/11/10 23:24:53 [error] 52514#0: *15 attempt to send data on a closed socket: u:0000000000000000, c:0000000000000000, ft:0 eof:0, 
2013/11/10 23:24:53 [error] 52514#0: *15 attempt to send data on a closed socket: u:0000000000000000, c:0000000000000000, ft:0 eof:0, 
```

I don't know if this one is actually related. Is there anything I can try to get more detail info where things actually broke. Server is FreeBSD with pf enabled, nginx 1.5.x.

Regards,

Uros

**Comment by xidianwlc** [comment]
你好，春哥：
       我最近测试redis连接池的部分，直接使用local ok, err = red:set_keepalive(10000, 100) 后进行ab压力测试，发现times, err = red:get_reused_times() 这个方法返回一直是times=0，日志一直报错：lua tcp socket connect timed out, client: 192.168.6.7  ，查看测试服务器到redis端口的连接数发现特别多，初步怀疑lua 的redis 连接池是不是有问题。我测试服务器为centos6.5 , nginx使用的是openresty最新版

**Comment by agentzh** [comment]
@xidianwlc Ah, please no Chinese here. This place is English only. If you really want to use Chinese, please join the openresty (Chinese) mailing list instead. Please see https://openresty.org/#Community

Regarding your question, it's already an FAQ. See my (Chinese) replies (to similar questions from others) on the aforementioned mailing list:

https://groups.google.com/d/msg/openresty/e-r69KtAWek/wJ3cdzxluhUJ

https://groups.google.com/d/msg/openresty/h3l6jAo3aD0/UvQGlF77cUwJ

**Comment by xidianwlc** [comment]
hi, agentzh:
      I try to use "local ok, err = red:set_keepalive(10000, 100)" in lua script and use "times, err = red:get_reused_times()" to check whether if the connection pool was used . But unexpected , times were always 0 and the error info  example are "lua tcp socket connect timed out, client: 192.168.6.7 "  .my nginx version is ngx_openresty-1.7.10.1

**Comment by agentzh** [comment]
@xidianwlc When you see "connect timed out", it usually means your redis server is too busy to accept new connections and the redis server's TCP stack is dropping packets when the accept() queue is full. You can consider

1. scale your redis backend to multiple node so as to utilize more CPU resources,
2. increase the backlog setting in your `redis.conf` file (the default is very small, which determines the length limit of your accept() queue on your redis server).
3. check whether your nginx server is too busy doing CPU intensive work or blocking system calls (like disk I/O syscalls) by using the flame graph tools: https://openresty.org/#Profiling
4. increase the timeout limit in your Lua code. Maybe you specify a too short timeout value on the client side?

**Comment by agentzh** [comment]
@xidianwlc Regarding the `get_reused_times` always returns 0 question, have you checked the return values of `set_keepalive`? My hunch is that you always fail to put your connections back to the connection pool in the first place so that your pool is always empty.

**Comment by xidianwlc** [comment]
@agentzh 
local ok, err = red:set_keepalive(10000, 800)
if not ok then 
    FORMAT_RETURN.msg="failed to set keepalive: "..err
    local value=cjson.encode(FORMAT_RETURN)
    ngx.say(value)
    ngx.log(ngx.ERR, value)
    return  
end

there were no nginx error log for this

**Comment by xidianwlc** [comment]
@agentzh I find some articles from https://groups.google.com/forum/#!topic/openresty/h3l6jAo3aD0 
 in the article you said the if connections are are bigger than connection pool ,it will use short connection

**Comment by agentzh** [comment]
@xidianwlc Isn't it already stated in the mailing list posts I mentioned earlier?

https://groups.google.com/d/msg/openresty/e-r69KtAWek/wJ3cdzxluhUJ

https://groups.google.com/d/msg/openresty/h3l6jAo3aD0/UvQGlF77cUwJ

Alas. you didn't read these carefully.

**Comment by agentzh** [comment]
@xidianwlc It's also officially documented:

https://github.com/openresty/lua-nginx-module#tcpsocksetkeepalive

"When the connection pool exceeds the available size limit, the least recently used (idle) connection already in the pool will be closed to make room for the current connection."

**Comment by RobinTsai** [comment]
I also met the error info "lua tcp socket connect timed out, when connecting to xxx:xxx"(xxx:xxx is the master redis server). We group had been working on it for several days. I checked a lot issues but there were no resolution. At last we used connection pool to decrease this error - but not fixed it.

It's on production env, and I'm sure the configure is no mistaken. On 3 different prod envs, one gived big chances of this error msg, the others are rarely. This one only have 2 cores (another one 8 cores and used 4 cores for thie nginx) but other sys config are totally same. And also same as redis. There are some info:

1. We set 100ms connect timeout when connect to redis master. When we adjust it up to 5s, the error just be less but not missing. (the other envs also set 100ms connection timeout, but there are not so much errors)
2. I capture the TCP (only when the connect timeout setting is 100ms), there are all normal TCP connection record: 3-handshakes, select db, get data, 4-waves. (Maybe the timeout is much little there are no retransmission. So I even thought the cpu just not process this event for the timeout-setting time.)

**Comment by zhuizhuhaomeng** [comment]
is the timeout issue occurred when you capture the TCP?

**Comment by RobinTsai** [comment]
Nop, there were not any clue for connection timeout issue. 

There were no SYN retransmition. And no packet just abnormal at SYN.

**Comment by RobinTsai** [comment]
Nop, there were not any clue for connection timeout issue. 

There were no SYN retransmition. And no packet just abnormal at SYN.

**Comment by RobinTsai** [comment]
Nop, there were not any clue for connection timeout issue. 

There were no SYN retransmition. And no packet just abnormal at SYN.

**Comment by zhuizhuhaomeng** [comment]
What did you mean by "abnormal at SYN"?

**Comment by RobinTsai** [comment]
If there were connect timeout, I thought, there might:
1. Have SYN Retransmit packets. >>> But there were not.
2. Have RST at the TCP stream. >>> But there were not.
3. Or, there might have incomplete 3-handshakes at TCP stream. >>> But there were not.

The TCP streams what I saw all were normal as expected.
