### ISSUE TITLE
lua entry thread aborted: runtime error: /usr/local/openresty/lualib/resty/redis.lua:357: bad request

### ISSUE THREAD

**Issue by ZxyNull0** [openresty/lua-resty-redis#270]
As long as I use concurrent requests to access OpenResty, the Lua code blocks encounter errors when executing Redis operations. Can you help me take a look?
```
2023/11/06 14:17:20 [error] 617753#0: *782440 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/resty/redis.lua:357: bad request
stack traceback:
coroutine 0:
	[C]: in function 'send'
	/usr/local/openresty/lualib/resty/redis.lua:357: in function 'hgetall'
```
other redis function such as `hgetall`、`hget`、`rpush` also  occurred  this problem as well

**Comment by ZxyNull0** [comment]
Translation: "Do I need to ensure atomic operations for each request? Will this issue not occur during sequential requests?

**Comment by ukiyowood** [comment]
How did you solve the problem？
