### ISSUE TITLE
[feature request] add ZRANDMEMBER command

### ISSUE THREAD

**Issue by 0xDEADFED5** [openresty/lua-resty-redis#281]
https://redis.io/docs/latest/commands/zrandmember/

**Comment by spacewander** [comment]
This should be supported yet. See https://github.com/openresty/lua-resty-redis?tab=readme-ov-file#methods

**Comment by 0xDEADFED5** [comment]
ERR unknown command `zrandmember`, with args beginning with: `views`, `25`, `WITHSCORES`, , client: 127.0.0.1, server: localhost, request: "GET /random HTTP/1.1", host: "localhost"

**Comment by spacewander** [comment]
This error message was returned from Redis. lua-resty-redis just forwards it.

**Comment by 0xDEADFED5** [comment]
oh man, i'm a little slow, thanks!
