### ISSUE TITLE
"attempt to yield across C-call boundary" occur while connect()

### ISSUE THREAD

**Issue by Laobei2012** [openresty/lua-resty-redis#3]
I package redis functions into a module testdb.lua, and include it in another module testm.lua.

testm.lua is required in test.lua, which is running by ngx_lua:

```
content_by_lua_file luas/test.lua;
```

Finally, the error occur:

```
2012/04/07 22:10:32 [error] 24794#0: *185113 1, client: 127.0.0.1, server: localhost, request: "GET /test HTTP/1.1"
2012/04/07 22:10:32 [error] 24794#0: *185113 lua handler aborted: runtime error: attempt to yield across C-call boundary, client: 127.0.0.1, server: localhost, request: "GET /test HTTP/1.1"
```

The first ngx.log() is excuted, but second not. So is there anything wrong in redis:connect()?

All the files could be found in: https://gist.github.com/2329313

thanks.

**Comment by yangm97** [comment]
Sorry if I’m stealing this issue, but I still don’t get how to work around this. Here’s my situation:

`database.lua`

```
local config = require 'config'

local red

if ngx then
	local redis = require 'resty.http'
	red = redis:new()
	red:connect(config.redis.host, config.redis.port)
else
	local redis = require 'redis'
	red = redis.connect(config.redis.host, config.redis.port)
end

red:select(config.redis.db)

return red
```

`main.lua` and many other “plugins”:

```
local db = require ‘database’
…
db:hset('bot:usernames', '@'..msg.from.username:lower(), msg.from.id)
...
```

So I have this wrapper mainly because my application can run either with or without openresty and because I wanted to avoid copy-pasting (the somewhat big) database connection code. 

The error message is the same (`lua entry thread aborted: runtime error: attempt to yield across C-call boundary`).

**Comment by agentzh** [comment]
@yangm97 Your usage is wrong. Please read the documentation more carefully:

https://github.com/openresty/lua-resty-redis/#limitations

**Comment by agentzh** [comment]
@yangm97 Also, read the discussion above.

**Comment by yangm97** [comment]
I read both. Also I kind see where it’s failing and why (_“The `resty.redis` object instance cannot be stored in a Lua variable at the Lua module level”_) but I really don’t see a solution other than copy-pasting 13 lines of code across ~30 files to work around this.

**Comment by seven1240** [comment]
seems set on ngx.ctx works for me

```
local resty_redis = require "resty.redis"
local redis = resty_redis:new()

redis:set_timeout(1000) -- 1 sec
ngx.ctx.redis = redis
```

**Comment by cleverpig** [comment]
> seems set on ngx.ctx works for me
> 
> ```
> local resty_redis = require "resty.redis"
> local redis = resty_redis:new()
> 
> redis:set_timeout(1000) -- 1 sec
> ngx.ctx.redis = redis
> ```

But it is a short lifetime(request) by using ngx.ctx
