### ISSUE TITLE
How do I skip/ignore errors generated under "content by lua"?

### ISSUE THREAD

**Issue by hwongcom** [openresty/lua-resty-redis#55]
How do I skip/ignore errors generated under "content by lua"?

1.i'm using 
local zlib = require "zlib"

sometimes the zlib variable returned will be empty or non compatible gzip format.

how do i let it continue to run?

2. how do i 

location ~ /cached/ {
                content_by_lua '
                       local zlib = require "zlib"
                        ...
                        ...
                        if (string.len(inflated) >= 10) then
                            ngx.say(inflated)
                            return
                          end';
}

how do i make it continue running the rest of the other status if it does not match string.len(inflated) ???

**Comment by agentzh** [comment]
Please do not cross-post. I have already answered your question in the other place. Also this question has nothing to do with this lua-resty-redis project. Closing this ticket.

BTW, you should use the openresty-en mailing list for such general questions.

**Comment by hwongcom** [comment]
sorry i remembered i posted somewhere but i cant remember which i posted because you have so many openresty related projects. i apologize

**Comment by hwongcom** [comment]
can you give me the location to the other post which you have answered? coz i not sure where the answer is.

**Comment by agentzh** [comment]
@hwongcom Let me repeat: please use the openresty-en mailing list for such things if you have no idea which openresty subproject it belongs to.
