### ISSUE TITLE
lua tcp socket read timed out

### ISSUE THREAD

**Issue by djhalaninext** [openresty/lua-resty-redis#57]
Hi, 
I have to track a change in a state of user and trigger a http post to another service based on http request from client. 

In my request method I am using nginx timer to create a subrequest and using redis pubsub to track state change.
```
ngx.timer.at(0, subscribe, params.tracker_user_uuid, target_user_uuid)
```

```
local function subscribe(premature, user_uuid, channel_id)
  local redis_x = require("redis.redis").new()
  local res, err = redis_x:subscribe("channel" .. channel_id)
  if not res then
      ngx.say("1: failed to subscribe: ", err)
      return
  end
  while true do
    local erver_url = "http://example.com"
    local res, err = redis_x:read_reply()
    if res then
      local req_body = res[3]
      local result, respcode, respheaders, respstatus = http.request({
        
      })
    end
    redis_x:set_keepalive(250, 200)
  end
end
```

I see following error every minute in my nginx log.
```
[error] 9938#0: lua tcp socket read timed out, context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:8080
```

Is this the best way to do this ?

**Comment by agentzh** [comment]
@djhalaninext Your code has a great risk of entering an infinite tight loop (thus maxing out CPU without doing anything good) when the `read_reply()` returns an error other than "read timeout", like "close" (when redis closes the connection prematurely). Always be VERY careful about `while true` loops.

**Comment by agentzh** [comment]
@djhalaninext Also, `set_keepalive` puts the underlying connection into the connection pool and shuts down the current `resty.redis` object and I don't think you want that upon every loop iteration. Better read the official documentation more carefully.

**Comment by agentzh** [comment]
@djhalaninext Another thing is that it's better to put `require()` on the top level of your Lua module instead of calling it everytime your function is called. `require` cannot be JIT compiled and it does not make sense to call it over and over again.

**Comment by agentzh** [comment]
@djhalaninext Always handle the errors of those `resty.redis` calls carefully in Lua, including `set_keepalive` and `read_reply`.

**Comment by agentzh** [comment]
@djhalaninext For redis subscribing, it's normal to get the `read timeout` error, which is not fatal at all. You just need to try `read_reply` again on the same `resty.redis` object. But as I've mentioned above, you MUST handle any other errors explicity without retrying `read_reply` blindly over and over again. Because for other fatal errors, any subsequent `read_reply` call will always return the "closed" error immediately, leading to hot tight looping in your example.

**Comment by agentzh** [comment]
@djhalaninext BTW, please use the openresty-en mailing list for such general discussions instead. Thank you for your cooperation! Please see http://openresty.org/#Community

**Comment by djhalaninext** [comment]
@agentzh  Thanks for all the input. Will fix and post more questions in openresty-en mailing list.
