### ISSUE TITLE
How to install it via luarocks?

### ISSUE THREAD

**Issue by MillerRen** [openresty/lua-resty-redis#63]
I'm tring install this lib via luarocks. It desn't work. But i see lots of lib named 'lua-resty-*'. Why not include this? I'm sorry my english is poor.

**Comment by agentzh** [comment]
@MillerRen No, this library does not support luarocks. Please read the documentation for installation instructions (or better, just use the OpenResty bundle directly). Thanks!

**Comment by MillerRen** [comment]
Thx
