### ISSUE TITLE
How to know if  is a redis key exits

### ISSUE THREAD

**Issue by surfire91** [openresty/lua-resty-redis#65]
hi, maybe it's a simple question, but it's a real question of mine and i get nothing from readme about this question. The question is how to know if is a redis key exists.

example:
```lua
local key = "not_exists"
local val, err = red:get(key)

if not val then
	ngx.say("the value is not exists.")
else 
	ngx.say("val: "..val)
end
```

when the key is not exits, I will get a error of `[error] 26052#0: *1678 lua entry thread aborted: runtime error: /opt/code/lua/redis.lua:22: attempt to concatenate local 'val' (a userdata value)`

I know that it's probably that the value is not exists, so i can not use `ngx.say()` to print it.
but I do not know how to figure out it with lua code, that I used `if not val`, `if val ~= nil`, which neither can not work correctly.

Thank you!

**Comment by bjoe2k4** [comment]
Quote from the `lua-resty-redis` documentation:
> A nil bulk reply results in a `ngx.null` return value.

Therefore you need to check against `ngx.null`:
```
if val == ngx.null then
    ngx.say("the value is not exists.")
else 
    ngx.say("val: "..val)
end
```

**Comment by surfire91** [comment]
Thank you for reply, I'm sorry have not focus on it.
I test it and it worked.

**Comment by bjoe2k4** [comment]
can you close the issue?

**Comment by Habbie** [comment]
(I understand I'm commenting on a closed issue which may mean nobody will remember to respond to this, will try harder later).

README.markdown has this snippet:
```lua
                local res, err = red:get("dog")
                if not res then
                    ngx.say("failed to get dog: ", err)
                    return
                end
```

and that's how I ran into this 'issue' as well. Is the README indeed wrong? Want me to submit a patch for it?

**Comment by agentzh** [comment]
No, the doc is correct and precise. Look more carefully.

**Comment by agentzh** [comment]
nil is returned for fatal errors like network problems, which is apparently a different thing.
