### ISSUE TITLE
an issue of an embeded connection pool

### ISSUE THREAD

**Issue by CCMBChina** [openresty/lua-resty-redis#67]
in nginx.conf,when using lua to connect redis,firstly,set_keeplive(1000,1000) in one location(such as location ^~ /appName/ {... }),and secondly,in anoteher location,connection to redis ,then set_keeplive(1000,500),now in one worker,is it exist only one connection pool?if only one pool,is its size 500 now?

QQQ(thank you) for everyone to answer this question!

**Comment by agentzh** [comment]
@CCMBChina To answer your questions:

1. cosocket connection pools are per worker (lua-resty-redis is based on cosockets).
2. you cannot change the size of existing connection pools unless the pools have been destroyed (like when there is no live connections in the pool).

BTW, such general questions should go to the openresty-en mailing list instead. This place is for *real* issues :) Thanks for your cooperation. Please see the following page for more details:

https://openresty.org/#Community
