### ISSUE TITLE
Limit connection pool size

### ISSUE THREAD

**Issue by slw** [openresty/lua-resty-redis#72]
After nginx restart high request rate lead to hundreds and thousands connections to redis and I see many errors like "lua tcp socket read timed out".
Can I limit connection pool size (and wait on connect() for released connection) for prvent this issuse?

**Comment by agentzh** [comment]
@slw We are working on connect() request automatic queueing based on the size of the cosocoket connection pool. When this feature is ready and used, you will no longer have this issue.

During the meantime, you can try the lua-resty-limit-traffic library to queue excessive backend connect() requests:

https://github.com/openresty/lua-resty-limit-traffic

**Comment by slw** [comment]
Thanks for replay!
Can you give some code example?
I am need only limit Redis connection, not incoming HTTP client connection.

**Comment by agentzh** [comment]
@slw Yes, lua-resty-limit-traffic can also limit backend traffic. There's no limitation on the context. See the resty.limit.conn module's manual for details (example included):

https://github.com/openresty/lua-resty-limit-traffic/blob/master/lib/resty/limit/conn.md

**Comment by ghprince** [comment]
@agentzh any update on the feature of auto queue on `connect()`?

**Comment by agentzh** [comment]
@ghprince You can use the lua-resty-limit-traffic library to limit backend concurrency. Not ideal but should be good enough for most common use cases.

**Comment by thibaultcha** [comment]
Connection queuing has been released as part of ngx_http_lua v0.10.14, and can be used via the new `pool_size` and `backlog` options of [tcpsock:connect](https://github.com/openresty/lua-nginx-module#tcpsockconnect).
