### ISSUE TITLE
redis:incr return value type is flaky

### ISSUE THREAD

**Issue by akashihi** [openresty/lua-resty-redis#77]
I'm using redis and lua to implement some counters on the nginx side with code like this:
`    local ret, err = redis:incr(callCountingKey)
    if ret > 300 then
        someActionHere()
    end
`

And sometimes comparision between ret and 300 throws "attempt to compare number with boolean". As far as i understand, redis incr command should always return a number. 300 is definitely a number. So, why sometimes ret becames boolean?

**Comment by agentzh** [comment]
@akashihi The `incr` method call may fail. You should always handle any errors before using the return value as data, for example,

```
local ret, err = redis:incr(callCountingKey)
if not ret then
    ngx.log(ngx.ERR, "failed to incr: ", err)
    -- take some other action here to handle the error...
end
if ret > 300 then
    someActionHere()
end
```

To quote the documentation of lua-resty-redis regarding boolean-typed return values of the redis operations:

> A Redis "error reply" results in a false value and a string describing the error.

See https://github.com/openresty/lua-resty-redis#methods for more details.

**Comment by akashihi** [comment]
My fault, sorry :)
