### ISSUE TITLE
Update your package version in luarocks please

### ISSUE THREAD

**Issue by zinovyev** [openresty/lua-resty-redis#80]
Current version is luarocks is [0.20-1](https://luarocks.org/modules/uuser/luarestyredis)

**Comment by agentzh** [comment]
@zinovyev As the maintainer of this library, I don't think we provide any official support for luarocks.

**Comment by zinovyev** [comment]
Oh that's a pity! I thought it's an official package. Sorry for that.
Even so luarocks is a convinient way to distribute your packages for many users.
If youl'd like to give it a try, probably I could help you with a rockspec file or something like that.

**Comment by agentzh** [comment]
@zinovyev We're working on the official OpenResty package manager right now. We don't like luarocks in its current shape.

**Comment by zinovyev** [comment]
Ok. Thank you for your reply! And sorry for taking your time)
