### ISSUE TITLE
about redis connect timeout :lua tcp socket read timeout

### ISSUE THREAD

**Issue by gholly** [openresty/lua-resty-redis#88]
hi：
   Why redis of hincrby so slow,solving？
  Code is as follows:
  Package redis as follows: (timeout 200000)
   redis的incrby为何这么慢，求解？
   代码如下：
   封装的redis如下： （timeout为0）

```
local redis = require "resty.redis"
local _M={}
_M.VERSION = '0.10'
local mt ={__index = _M}

function _M.new(self,opt)
  local ip       =  opt.ip       or "127.0.0.1"
  local port     =  opt.port     or  6379
  local timeout  =  opt.timeout  or 0
  local idletime =  opt.idletime or  10000
  local poolsize =  opt.poolsize or  100

return setmetatable({ip = ip ,
                     port = port,
                     timeout = timeout,
                     idletime = idletime,
                     poolsize = poolsize},mt)

end

local function _connect(self)
local red = redis :new()

red:set_timeout (self.timeout)
local ok,err = red:connect(self.ip , self.port)
if not ok then
    return nil ,err
end
return red,nil
end

local function _set_keepalive(self,red)
red:set_keepalive(self.idletime , self.poolsize)
end



function _M.cmd(self,command,...)
local red, err = _connect(self)
if err then
    return nil, err
end
local cmd_fun = red[command]
local res, err =cmd_fun(red, ...)
if nil == err then
    _set_keepalive(self, red)
end

return res,err
 end



return _M


运用redis的代码如下：
 local rds = new_redis:new(config.rdsconf)
 local res,err =rds:cmd("incrby", "count_XXXXXXXXXXXX_XXXXXX", "1")
 if err ~= nil then
  ngx.log(ngx.ERR,"err: ",err," count_XXXXXXXXXXXX_XXXXXX  1")
  return
 else        
  return res
 end
```

和

```
  local rds = new_redis:new(config.rdsconf)
  local res,err = rds:cmd("lpush", "modus", cjson.encode(ModuleInfo))

  if nil == err then     
   ngx.log(ngx.INFO,"success")
  else
   ngx.log(ngx.ERR,"redis lpush modus ",err)
  end
```

Running frequently reported timeout errors, leading to redis lpush key failure, and lua tcp socket read timed out, and redis-server version is 3.0,
What is the problem? What is the solution? Solving

**Comment by agentzh** [comment]
Maybe your resty.redis timeout threshold is set to a too small value? I don't see your timeout settings. BTW, your code example is not standalone.

**Comment by gholly** [comment]
the timeout threshold is 200000(200s),the code running 20 minutes will reported timeout errors, and lua tcp socket read timed out.

**Comment by agentzh** [comment]
This is strange. Will you prepare a minimal and standalone example that I can easily run and reproduce the timeout issue on my side?

**Comment by gholly** [comment]
File  new_redis.lua：


    local redis = require "resty.redis"
    local _M={}
     _M.VERSION = '0.10'
     local mt ={__index = _M}

     function _M.new(self,opt)
       local ip       =  opt.ip       or "127.0.0.1"
       local port     =  opt.port     or  6379
       local timeout  =  opt.timeout  or 0
       local idletime =  opt.idletime or  10000
       local poolsize =  opt.poolsize or  100

      return setmetatable({ip = ip ,
                     port = port,
                     timeout = timeout,
                     idletime = idletime,
                     poolsize = poolsize},mt)

     end

     local function _connect(self)
     local red = redis :new()

     red:set_timeout (self.timeout)
     local ok,err = red:connect(self.ip , self.port)
     if not ok then
         return nil ,err
     end
    return red,nil
    end

     local function _set_keepalive(self,red)
         red:set_keepalive(self.idletime , self.poolsize)
     end

     function _M.cmd(self,command,...)
       local red, err = _connect(self)
       if err then
          return nil, err
       end
     local cmd_fun = red[command]
     local res, err =cmd_fun(red, ...)
     if nil == err then
         _set_keepalive(self, red)
    end

    return res,err
    end



    return _M


file config.lua


      local _M={}
       _M.VERSION = '0.10'
      local mt ={__index = _M}
       _M.rdsconf = {ip = "192.168.3.194",
			  timeout=200000,
			  idletime=10000,
			  poolsize=1000,
              port = 6380}

      return _M

file  app.lua
 
        local new_redis = require "resty.new_redis"
        local config = require "resty.config"

        local rds = new_redis:new(config.rdsconf)
	local res,err =rds:cmd("incrby", "digest_id_auto_increment_val_by_incrby_redis_20160707", "1")
	if err ~= nil then
		ngx.log(ngx.ERR,"err: ",err,"redis incrby digest_id_auto_increment_val_by_incrby_redis_20160707  1")
		return
	else		 
		ngx.say(res)
	end 

the file config.lua and new_redis.lua are locationed at "/usr/local/openresty/lualib/resty/".
the error log info :
1)err:connection timeout,redis incrby digest_id_auto_increment_val_by_incrby_redis_20160707
2)(110 :connection timeout)

3)err:connection reset by peer,redis incrby  digest_id_auto_increment_val_by_incrby_redis_20160707

**Comment by gholly** [comment]
the resty redis connections are 190,the redis server connections are total 2200 that contains other interface server not for openresty.

**Comment by agentzh** [comment]
Maybe your redis server is just too busy? Try starting an isolate redis server dedicated for your test.

**Comment by agentzh** [comment]
Also your example does not look like minimized. Try removing as much irrelevant Lua code as possible while preserving the issue. So much Lua code can easily contains bugs itself and we do not have the time to debug issues in your own Lua code.

Finally, specify how we should initiate test requests to the test server in order to reproduce the issue and tell us how easy and how frequently we can reproduce the problem. Just provide as much details as possible and do not make us guess.

**Comment by rupamkhaitan** [comment]
We ran with an isolated redis server which is not doing anything
We run a lua code from another box with a very minimal code (posted in https://github.com/openresty/lua-resty-redis/issues/123 )

But still we see after the request the redis connection goes into TIME_WAIT state (it doesnt stay till 100 seconds we configured)

**Comment by rupamkhaitan** [comment]
Here is the config file

worker_processes  1;
error_log logs/error.log;
events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;
        location /test {
		lua_code_cache on;
   	 content_by_lua_block {
        	local redis = require "resty.redis"
    	    	local red = redis:new()
        	red:set_timeout(500000) -- ms
   	     	ok, err = red:connect("10.140.134.38", 6379)
       		if not ok then
        		ngx.say("failed to connect redis: ", err)
        	end
        	-- ngx.sleep(3) -- tcp status : ESTABLISHED
       		 local ok, err = red:set_keepalive(1000000, 10) -- tcp status : TIME_WAIT
        	if not ok then
                    ngx.log(ngx.ERR, "set keep alive error", err);
        		ngx.say("failed to set keepalive: ", err);
        	end
	    }
	}
    }
}

**Comment by agentzh** [comment]
@rupamkhaitan Please do not hijack unrelated issues.

**Comment by rupamkhaitan** [comment]
@agentzh i posted the new issue.. sorry

**Comment by rupamkhaitan** [comment]
@agentzh sorry i have posted new issue here https://github.com/openresty/lua-resty-redis/issues/140
