### ISSUE TITLE
`no request found`

### ISSUE THREAD

**Issue by jney** [openresty/lua-resty-redis#89]
executing the code:

```lua
local redis = require('resty.redis')
local red = redis:new()
```

I've got the following error

```
2016/06/28 16:34:42 [error] 62#0: [lua] kong.lua:168: init(): Startup error: /app/.heroku/share/lua/5.1/kong/tools/utils.lua:211: /app/.heroku/lualib/resty/redis.lua:101: no request found
```

**Comment by agentzh** [comment]
@jney I guess you run that piece of code in a wrong context like `init_by_lua*`?

See

https://github.com/openresty/lua-resty-redis#limitations

**Comment by jney** [comment]
hi @agentzh, i'm using kong heroku's buildpack. isn't it supposed to work out of the box ?

**Comment by agentzh** [comment]
@jney I'm not a developer of Kong nor Heroku. Maybe you should contract the Kong or the Herku team instead? Otherwise you have to use OpenResty's terminology for us to understand your use cases.

**Comment by jney** [comment]
regarding this ticket: Mashape/kong#1349 you can close this ticket
