### ISSUE TITLE
cannot connect while providing hostname

### ISSUE THREAD

**Issue by mathusiast** [openresty/lua-resty-redis#9]
Given the following code:

```
local redis = require "resty.redis"

REDIS_HOST = "127.0.0.1"
REDIS_PORT = 6379

redis_client = redis:new()

local ok, err = redis_client:connect(REDIS_HOST, REDIS_PORT)
```

If `REDIS_HOST` is `"localhost"` instead of `127.0.0.1`, then it failed to connect.

Although, in the scope of `localhost` vs. `127.0.0.1` it makes no difference, in a real world dynamic production environment, an IP is not likely to be used, rather, a nameserver instead.

**Comment by viatcheslavmogilevsky** [comment]
This is my workaround.
It will maybe usefull:


```
# you can specify resolver in nginx location where you use lua directives
location ~ ^/redis_test {
        resolver 10.0.0.2;
        content_by_lua '
                local redis = require "resty.redis"
                local red = redis:new()

                red:set_timeout(1000) -- 1 sec

                -- or connect to a unix domain socket file listened
                -- by a redis server:
                --     local ok, err = red:connect("unix:/path/to/redis.sock")

                local ok, err = red:connect("redis.host.internal", 6379)
                if not ok then
                    ngx.say("failed to connect: ", err)
                    return
                end

                ngx.say("this is test")

                -- or just close the connection right away:
                local ok, err = red:close()
                if not ok then
                  ngx.say("failed to close: ", err)
                  return
                end
            ';
      }
```

**Comment by linsheng9731** [comment]
hi, @tzuryby , i got same problem when used openresty inside docker container. The service cound not connected redis properly, the message showed 'cant not resolve host properly'. The reason is the nginx built-in resolver does not support the /etc/hosts configure, so i installed dnsmasq and run a native dns resolver, fortunately, it worked. May help good luck :)

**Comment by yangm97** [comment]
@linsheng9731 you could’ve simply used docker DNS resolver: 127.0.0.11
