### ISSUE TITLE
red:connect("127.0.0.1", 6379)  , can use the domain name?

### ISSUE THREAD

**Issue by kangdong** [openresty/lua-resty-redis#91]
red:connect("127.0.0.1", 6379)  , can use the domain name?

**Comment by agentzh** [comment]
@kangdong Yes. But you must configure the standard `resolver` directive in your `nginx.conf`:

http://nginx.org/en/docs/http/ngx_http_core_module.html#resolver

**Comment by sergey-shambir** [comment]
More information in #9
