### ISSUE TITLE
redis.call caused the nginx error: attempt to call field 'call' (a nil value)

### ISSUE THREAD

**Issue by Sail64** [openresty/lua-resty-redis#95]
Hi,

I need to use the redis.call function to get results via zrangebyscore from redis:

    nginx:~/redis# redis-cli -p 6379
    127.0.0.1:6379> eval "return redis.call('zrangebyscore', 'range', '1234122334', '+inf', 'limit', '0', '1')" 0 1
    1) "<1249409024,null"

I get the correct result under redis-cli.

But when I used in openresty, get **nil** error from nginx, the config is below:

    server {
        listen       80;
        listen       443;
        server_name  xxx;

        location = /info.json {
            content_by_lua_file '/usr/local/openresty/nginx/redis/info.lua';
        }

**Question 1**

info.lua:

    local redis = require "resty.redis"
    local red = redis:new()
    red:set_timeout(g_cache.redis_timeout)

    local ok, err = red:connect(g_cache.redis_host, g_cache.redis_port, {pool="mypool"})
    if not ok then
      ngx.log(ngx.ERR, "[CACHE] redis server failed to connect: ", g_cache.redis_host, g_cache.redis_port)
      return ngx.exec(g_cache.err_return_page)
    end
    ...
    redis_res = redis.call('zrangebyscore', 'range', '12341232', '+inf', 'limit', '0', '1')
    ...

nginx error.log:

    2016/08/19 15:15:49 [error] 74657#0: *1922828 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/redis/info.lua:40: **attempt
    to call field 'call' (a nil value)**
    stack traceback:
    coroutine 0:
            /usr/local/openresty/nginx/redis/info.lua: in function </usr/local/openresty/nginx/redis/info.lua:1>, client: x.x.x.x, server: xxx, request: "GET /info.json HTTP/1.1", host: "xxx"

**Question 2**

After I get this error, I used eval instead as below:
info.lua:

    redis_res, err = red:eval("return redis.call('zrangebyscore', 'range', '12341232', '+inf', 'limit', '0', '1'", 0, 1)

And I got the **false** value of redis_res.

Could you please give me some advice to solve this issue.

**Comment by spacewander** [comment]
What is the value of `err` in **Question 2**? `redis_res` will be `false` when something goes wrong.

**Comment by agentzh** [comment]
@Sail64 Ensure you are using the latest version of this library (or the latest OpenResty 1.11.2.1 RC1 bundle).

Also ensure you always check the error string returned which contains the reason of the failure.

It seems that you can directly call the `zrangebyscore` method on your resty.redis object? Why calling redis-side Lua here?

**Comment by Sail64** [comment]
@spacewander
I printed the err, and found a ')' was missing in the command line.

    redis_res, err = red:eval("return redis.call('zrangebyscore', 'range', '12341232', '+inf', 'limit', '0', '1'", 0, 1)

I added it:

    redis_res, err = red:eval("return redis.call('zrangebyscore', 'range', '12341232', '+inf', 'limit', '0', '1')", 0, 1)

And it returned the normal result.
Thank you for your tip.

**Comment by agentzh** [comment]
Consider it resolved.

**Comment by Sail64** [comment]
I use this code:

    redis_res, err = red:zrangebyscore('iprange', ip, '+inf', 'limit', '0', '1')
    
to replace the eval+redis.call method, it works, and has better performance and is more flexible.
Thank you for your reply.
