### ISSUE TITLE
redis hgetAll and get response

### ISSUE THREAD

**Issue by adaksuman** [openresty/lua-resty-redis#96]
hi, 
I wanted to catch error if I dont find keys in redis. So I tried to do like

local res,err = redis:hgetall("test")
if not res then
   ngx.say("not found")
  return
end

even for redis:get("test1") same error handing is not working. I changed to check with ngx.null , its now working.
local res,err = redis:get("test")
if res == ngx.null then
   ngx.say("not found")
  return
end

Just wondering,  where am I doing wrong? All test case has been written with above code. I am using latest redis with latest openresty release.  Anything changed in redis protocol?

**Comment by agentzh** [comment]
@adaksuman `hgetall` returns an array value:

http://redis.io/commands/hgetall

So when it does not return any keys, it return an empty array, which is an empty Lua table on the Lua land. In Lua, an empty Lua table is a true value when being evaluated in the boolean context.

Please join the openresty-en mailing list for such questions in the future. This place is for bug reports and feature/patch discussions only. Thanks for your cooperation.

**Comment by agentzh** [comment]
@adaksuman BTW, `ngx.null` is a true value as well. You can easily test that yourself in Lua anyway.

**Comment by agentzh** [comment]
@adaksuman Read the code sample in the official docs more carefully on how to handle errors: https://github.com/openresty/lua-resty-redis#synopsis The rest of the documentation has more detailed explanation. Please read it.
