### ISSUE TITLE
redis  key中下划线等特殊字符的情况

### ISSUE THREAD

**Issue by Chen235** [openresty/lua-resty-redis#97]
您好，我碰到一个问题：使用openresty redis模块获取redis值时，当key中含有下划线时，总是获取失败。
我的openresty版本：1.9.3.2，服务器版本：centos 6.5
请问这个是什么问题，是否还有其他特殊情况？多谢！

**Comment by agentzh** [comment]
@Chen235 Please do not use Chinese here. This place is considered English only. If you really want to use Chinese, please join and post to the openresty (Chinese) mailing list instead. Please see http://openresty.org/en/community.html

**Comment by agentzh** [comment]
@Chen235 Regarding your question, I've just added a test case to the existing test suite exercising the case using redis keys with an underscore character:

https://github.com/openresty/lua-resty-redis/blob/master/t/sanity.t#L780

And the test passes successfully on my side.

**Comment by agentzh** [comment]
@Chen235 BTW, OpenResty 1.9.3.2 is antient. The latest release is 1.11.2.1.

If you still believe it's an issue in this library, please provide a minimal and standalone example that can reproduce the problem easily on our side. Thank you.
