### ISSUE TITLE
use in ssl_session_store_by_lua,error.log:cannot yield in sess get cb: missing async sess get cb support in OpenSSL while fetching SSL session by lua

### ISSUE THREAD

**Issue by lvkegarden** [openresty/lua-resty-redis#98]
nginx.conf:
```
server {
        add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
        listen       443 ssl http2 ;
        server_name  localhost;

        ssl_certificate      ./ssl/server.crt;
        ssl_certificate_key  ./ssl/server.key;

       # ssl_session_cache    shared:SSL:1m;
       # ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;


        #ssl_stapling on;ssl_stapling_file ocsp.staple;

        ssl_session_store_by_lua_file conf/lua/session_store.lua;
        ssl_session_fetch_by_lua_file conf/lua/session_fetch.lua;


        #test redis
        #rewrite_by_lua_file  conf/lua/thumbnail.lua;

        location / {
            root   html;
            index  index.html index.htm;
        }
    }
```

session_fetch.lua:
```
local redis = require "resty.redis"
                local red = redis:new()

                red:set_timeout(1000) -- 1 sec

                -- or connect to a unix domain socket file listened
                -- by a redis server:
                --     local ok, err = red:connect("unix:/path/to/redis.sock")

                local ok, err = red:connect("10.171.122.122", 6379)
                if not ok then
                    ngx.say("failed to connect: ", err)
                    return
                end

                ok, err = red:set("dog", "an animal")
                if not ok then
                    ngx.say("failed to set dog: ", err)
                    return
                end
```

error.log
`cannot yield in sess get cb: missing async sess get cb support in OpenSSL while fetching SSL session by lua`

**Comment by lvkegarden** [comment]
If the file is modified
session_fetch.lua:
			```
	local redis = require "resty.redis"
                local red = redis:new()

                red:set_timeout(1000) -- 1 sec

                -- or connect to a unix domain socket file listened
                -- by a redis server:
                --     local ok, err = red:connect("unix:/path/to/redis.sock")

                local ok, err = red:connect("10.171.122.122", 6379)
                if not ok then
                    ngx.say("failed to connect: ", err)
                    return
                end
```

error.log don't show above error

**Comment by agentzh** [comment]
@lvkegarden The error message you're getting says it all. Your OpenSSL does not support it. To quote the documentation of `ssl_session_fetch_by_lua_block`:

> If you are using the official pre-built packages for OpenResty 1.11.2.1 or later, then everything should work out of the box.
> 
> If you are using OpenSSL libraries not provided by OpenResty, then you need to apply the following patch for OpenSSL 1.0.2h or later:
> 
> https://github.com/openresty/openresty/blob/master/patches/openssl-1.0.2h-sess_set_get_cb_yield.patch
> 
> If you are not using the NGINX core shipped with OpenResty 1.11.2.1 or later, then you need to apply the following patch to the standard NGINX core 1.11.2 or later:
> 
> http://openresty.org/download/nginx-1.11.2-nonblocking_ssl_handshake_hooks.patch

Quoted from https://github.com/openresty/lua-nginx-module#ssl_session_fetch_by_lua_block

Please do read the official documentation carefully.

**Comment by cltxiaoyao** [comment]
My openresty version is 1.9.15.1 and openssl version is 1.0.2h, I apply the following patch for the openssl,
https://github.com/openresty/openresty/blob/master/patches/openssl-1.0.2h-sess_set_get_cb_yield.patch
![image](https://cloud.githubusercontent.com/assets/22709589/19213240/84c82976-8d98-11e6-922e-08bc7829ffa6.png)

the error.log is also:
cannot yield in sess get cb: missing async sess get cb support in OpenSSL while fetching SSL session by lua

**Comment by agentzh** [comment]
@cltxiaoyao Are you 100% sure your openresty's nginx executable is linking against the right libcrypto.so library at runtime? The easiest way to find it out is to use the `ldd` command.

Your error.log message unambiguously indicates that the actual openssl used by the process lacks the patch. Or you just forgot to restart your server (reload won't update the binary BTW).

It's recommended to use the official binary packages provided by OpenResty whenever possible:

http://openresty.org/en/linux-packages.html

We're adding support for Ubuntu and Debian soon as well.

**Comment by cltxiaoyao** [comment]
Because I used OpenSSL 0.9.8j ,now I have updated to version 1.0.2h,so I want to recompile the nginx. The problem has resolved now. Thank you for your guidance!
