### ISSUE TITLE
lualib/resty/redis.lua:253 send crash

### ISSUE THREAD

**Issue by wynelu** [openresty/lua-resty-redis#99]
Hi, i had a problem using lua-resty-redis, error log can find in nginx log, like below:

2016/09/28 04:24:14 [error] 22348#0: *560 [lua] affiliate_reflex.lua:212: stack traceback:
	...e/work/reflex_chain/lua/affiliate_reflex.lua:212: in function <...e/work/reflex_chain/lua/affiliate_reflex.lua:212>
	[C]: in function 'send'
	/home/work/openresty/lualib/resty/redis.lua:253: in function 'get'
	...ork/reflex_chain/lua/helper/redis_helper.lua:75: in function 'get'
	/home/work/reflex_chain/lua/helper/util.lua:101: in function 'get_cache'
	...e/work/reflex_chain/lua/affiliate_reflex.lua:131: in function <...e/work/reflex_chain/lua/affiliate_reflex.lua:35>
	[C]: in function 'xpcall'
	...e/work/reflex_chain/lua/affiliate_reflex.lua:212: in function <...e/work/reflex_chain/lua/affiliate_reflex.lua:1>, client: 172.31.50.125, server: 172.31.50.227, request: "GET /redirect?id=MTQ3NDU1NDg2MzYtMTY=&subpub=se_gb_0923&aff_sub1=13c959e8baf9df45%7C0.08%7Cse%7Ccom.funplus.kingofavalon%7C80%7C%7C%7C%7C%7C2740147%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C HTTP/1.1",

but i have no idea why redis send failed, every time before redis command get , i connect once.

looking forward to your reply.
thanks

**Comment by agentzh** [comment]
I have never seen this before. Please provide a minimal and standalone example that can easily reproduce the problem on our side. Thank you.

**Comment by wynelu** [comment]
Thanks, after debug and google, I find my error was the same as below : 

https://github.com/openresty/lua-resty-redis/issues/44

I defined A local connection in my redis helper file, so perhaps multi request use the same connection, leading to crash. 
After reading issues 44,  I remove the variable and new everything looks fine.

Thanks very much.

**Comment by agentzh** [comment]
You cannot make multiple request handlers share the same cosocket object. It's explicitly documented. Fix your own Lua code and avoid such bad uses.
